### ISSUE TITLE
How to create pmtiles?

### ISSUE THREAD

**Issue by joernheissler** [protomaps/PMTiles#10]
Hello,
how can I create my own pmtiles?

**Comment by bdon** [comment]
Right now the only writer implementation I have published is the Python one: https://github.com/protomaps/PMTiles#how-to-use

**Comment by gibbsnich** [comment]
Can you tell me which tool you used to generate the mbtiles file (which is then input for `pmtiles-convert`)?  
I tried generating mbtiles files with https://github.com/openmaptiles/openmaptiles and https://github.com/systemed/tilemaker but the resulting pmtiles file is off somehow..
Thank you!

**Comment by reyemtm** [comment]
For raster tiles, you can generate mbtiles using any of the following methods:
 - QGIS > Generate XYZ tiles (mbtiles)
 - Use one of the many forks of the gdal2tiles python tool called [gdal2mbtiles](https://github.com/ecometrica/gdal2mbtiles) - just one example
 - Convert a folder tree of an already tiled raster and use the [mbutil](https://github.com/mapbox/mbutil) python tool to package these images into an mbtiles file.

**Comment by gibbsnich** [comment]
Thanks for those recommendations! Will definitly take a closer look. Also..
Did you try to generate an mptiles files from the mbtiles generated with the tools you listed? Did that work? What would you use for vector tiles?
If I‘m understanding it correctly openmaptiles uses TMS instead of XYZ; that could be the problem why those mbtiles don‘t work for me..

**Comment by bdon** [comment]
Yes, the converter needs to be fixed to always use TMS for mbtiles input: https://github.com/protomaps/PMTiles/issues/8

**Comment by bdon** [comment]
@gibbsnich can you try upgrading to 0.0.5? MBTiles coords should now be properly interpreted as TMS.

@reyemtm on the subject of gdal2pmtiles, it would share most of the logic with gdal2mbtiles, but the last bit of inserting into SQLite is replaced by writing to a stream and managing the directory creation.

 In my experience, programs need to use either the GDAL python bindings or C bindings, and the difficulty is making it work for whatever GDAL is on a user's machine, whether it's through Python or a dynamic library. Using the C library will be much faster but still demands having a solution for distributing it to end users.

Maybe another option is to have the pmtiles just use Rasterio as a dependency so we would inherit all the packaging/linking bits (the hard part) from that.

**Comment by gibbsnich** [comment]
Yes, 0.0.5 fixes this issue

**Comment by reyemtm** [comment]
I successfully created a pmtiles but am wondering if the algorithm you
discuss in your latest blog is present in this version or if that was just
a theory, treating a map like a video. From the blog post I imagined the
pmtiles would be smaller than the mbtiles file but maybe I am missing
something.

**Comment by bdon** [comment]
@reyemtm yes, it will deduplicate tiles based on their hash https://github.com/protomaps/PMTiles/blob/master/python/pmtiles/writer.py#L28 

It's possible your MBTiles does not have duplicate data, or your MBTiles already implements deduplication by using a view.
