### ISSUE TITLE
Unclear Metadata (JSON?) spec

### ISSUE THREAD

**Issue by nyurik** [protomaps/PMTiles#111]
The v2 of the spec mentions that metadata must be a proper json:

> Followed by M bytes of metadata, which must be a JSON string with bounds, minzoom and maxzoom properties (new in v2)

In v3, it seems all requirements for metadata are gone, with some fields (bounds, zooms, etc) are now part of the fixed header.  Are there any specs, or even just recommendations for consistency of the fields that are still part of the JSON? There seem to be some expectations in [this code](https://github.com/protomaps/PMTiles/blob/af409af0437b20ff4a9e3ba95004392c023edbb9/app/src/MaplibreMap.tsx#L101) of `tilestats` and `vector_layers` -- the later is probably part of tilejson spec, but what is the `tilestats`?

Lastly, unrelated - could you rename the `spec.md` to `README.md` in those dirs? makes browsing a bit easier :)

**Comment by bdon** [comment]
the json metadata is intended to be application specific. I'm probably going to add `vector_layers` as defined by https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#vector_layers but maybe limited to just `id` instead of having to enumerate all fields (what about tiles where the # of tags is not a fixed tabular schema, for example?) but haven't formalized it out of caution for unexpected but common use cases.  

`tilestats` is something generated by Tippecanoe already which includes summary statistics. This is necessary if you want to style your map based on min and max like a choropleth.

**Comment by bdon** [comment]
Current things under consideration:

* `type:baselayer`if the raster or vector tileset is a basemap; if this is NOT true, like `type:overlay`, a client can visualize the tileset over a basemap
* `vector_layers:` generally following MBTiles/TileJSON but looser language to allow for describing OSM QA Tiles https://osmlab.github.io/osm-qa-tiles/
   *Maybe adding another value indicating all of the geometries in a vector tile layer are the same geometry type? MVT allows heterogeneous layers, but in practice many systems emit only one geometry type per layer.

**Comment by bdon** [comment]
@nokonoko1203 @nyurik @msbarry this is the minimal refinement to the spec I'm going propose: https://github.com/protomaps/PMTiles/pull/123

Note that http://github.com/felt/tippecanoe already behaves exactly this way.

How it affects other programs:

Program to convert from MBTiles to PMTiles needs to check for the existence of a `json` key in metadata, and extract the two sub-keys `vector_layers` and `tilestats` into separate keys

Going the other way, check for the existence of `vector_layers` and `tilestats` and create a new `json` key in MBTiles metadata

## Other stuff

I'm not 100% happy with the `vector_layers` as specified in MBTiles. Spec 1.3 states " future revision of this specification will delegate the description of the json row of the metadata table to an external specification." but I wouldn't depend on this happening. The specific problems I see are:
* `vector_layers` does not provide any hints as to the geometry type of a layer - we could add an optional `geom_type` so a inspector client does not need to create 3 maplibre layers point/line/fill for EVERY vector_layer
* `vector_layers` > `fields` does not describe what happens for open-ended schemas like QA tiles / all of OSM. It's unwieldy to track and write thousands of keys here (think about just all the `name:*` keys)

However, if roundtrip conversion between pmtiles <-> mbtiles is important, then that might limit what we can really improve here.

**Comment by bdon** [comment]
As described above, detail added to [spec 3.1](https://github.com/protomaps/PMTiles/blob/main/spec/v3/spec.md#metadata) on `vector_layers` and `type` as well as other fields. No surprises here, just stick to what works for existing tooling.
