### ISSUE TITLE
KeyError: 'center'

### ISSUE THREAD

**Issue by eddy-geek** [protomaps/PMTiles#113]
I get this on pmtiles-convert of a file without "center".

```python
from pmtiles import convert
convert.mbtiles_to_pmtiles('Sorbetto.mbtiles', 'Sorbetto.pmtiles', None)
File /ything/software/anaconda3/lib/python3.10/site-packages/pmtiles/convert.py:24, in mbtiles_to_header_json(mbtiles_metadata)
     21 header["max_lon_e7"] = int(float(bounds[2]) * 10000000)
     22 header["max_lat_e7"] = int(float(bounds[3]) * 10000000)
---> 24 center = mbtiles_metadata["center"].split(",")
     25 header["center_lon_e7"] = int(float(center[0]) * 10000000)
     26 header["center_lat_e7"] = int(float(center[1]) * 10000000)

KeyError: 'center'
```

I don't think it's mandatory, and anyway it's better for compatibility to compute it from bounds if absent? (the file is from https://drive.google.com/drive/folders/1ZcGzbGJsDKxP4c5aXHjBxMy3FVsNaNkN?usp=sharing but has nothing special otherwise ;))

**Comment by bdon** [comment]
It is mandatory. This is somewhat influenced by conversion to/from MBTiles. A writer should at minimum set center lon/lat at the midpoint of bounds and center zoom = minzoom. I would rather have that small bit of default logic in writer programs (of which there are only a few) than in reader programs.

**Comment by eddy-geek** [comment]
ok, I was speaking from memory of the admitted old MBTiles 1.1 spec
but no worry, I just changed my code to add this first
