### ISSUE TITLE
Demo broken on Chrome/OS X.

### ISSUE THREAD

**Issue by bmschmidt** [protomaps/PMTiles#114]
Great project I've been following with interest.

----

I find the zip code demo linked from the repo does not work for me. (OS X, Chrome 108). Screenshots in case they are is useful.

<img width="925" alt="image" src="https://user-images.githubusercontent.com/1110758/212551525-2e599eb4-21c8-4052-90da-375a5a10bfce.png">

<img width="637" alt="image" src="https://user-images.githubusercontent.com/1110758/212551592-9b55dbae-2e17-4edb-b89a-fed2d2408968.png">

```
<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><BucketName>protomaps-static</BucketName><RequestId>tx000000000000003e036d4-0063c42212-2d8da7eb-sfo3a</RequestId><HostId>2d8da7eb-sfo3a-sfo3-zg01</HostId></Error>
```

**Comment by bdon** [comment]
Thanks, I just had to update the outdated link.
