### ISSUE TITLE
Infinite loop when writing tiles not in increasing order

### ISSUE THREAD

**Issue by rphlo** [protomaps/PMTiles#115]
With the python package, it seems that writing tiles with tile_id not in increasing order result in infinite loop when finalising the pmtiles file.

**Comment by bdon** [comment]
Yeah, we should fix that; were you able to resolve this by writing them in increasing order? We can either enforce the order or re-sort the entries in the last step

**Comment by bdon** [comment]
Resolved in [python pmtiles v3.2.0](https://pypi.org/project/pmtiles/) - you don't need to do anything special, it will detect unordered writes and set `clustered=false` (though this is not optimal - prefer ordered writes if possible)
