### ISSUE TITLE
AVIF support

### ISSUE THREAD

**Issue by rphlo** [protomaps/PMTiles#116]
On the web AVIF support is quite wide and has better compression ratio than webp.
Would it be an option to add AVIF in the possible TileType in the specification?

**Comment by bdon** [comment]
I think it's a good idea. For now, setting `0` (unknown) for the TileType enum should work fine - is that an interim solution for your use case?

**Comment by bdon** [comment]
I think the JS should just work, it should pass the bytes through to the browser's `Image` APIs; the metadata is mostly useful for JS to distinguish between vector and raster tiles, or for other non-browser consumers to do image operations on the tiles. Let me know if you run into issues.

**Comment by bdon** [comment]
PR for JS client: https://github.com/protomaps/PMTiles/pull/200

**Comment by bdon** [comment]
[python pmtiles v3.2.0](https://pypi.org/project/pmtiles/) has the AVIF value as well as C++ header.
