### ISSUE TITLE
Question: FileSource JS Example 

### ISSUE THREAD

**Issue by ameykshirsagar** [protomaps/PMTiles#118]
Hi,
I am learning how to use PMTiles with a simple file upload form. Can anyone please help me with a working example with MaplibreJS??

Thank you

**Comment by ameykshirsagar** [comment]
I am trying to make it work using svelte. Here is my App.svelte.
After uploading a file, I am getting this error
```
Uncaught Error: Unimplemented type: 6
```
Steps to recreate my issue
1. npm create vite@latest
2. Select Svelte. And change directory to project folder.
3. npm i pmtiles
4. npm run dev

`````javascript
<script>
  import {
    PMTiles,
    FileAPISource,
    Protocol
  } from "pmtiles";
  import {
    onMount
  } from "svelte";
  let mapBlob, mapEl, downloadMap, files;

  function onFilesLoad() {
    console.log(files[0]);
    let protocol = new Protocol();
    maplibregl.addProtocol("pmtiles", protocol.tile);
    let PMTILES_URL = new FileAPISource(files[0]);
    const p = new PMTiles(PMTILES_URL)
    protocol.add(p);
    p.getHeader().then(h => {
      const map = new maplibregl.Map({
        container: mapEl,

        zoom: h.maxZoom - 2,
        center: [h.centerLon, h.centerLat],
        style: {
          version: 8,
          sources: {
            "example_source": {
              type: "vector",
              url: "pmtiles://maps.pmtiles",
              attribution: '© <a href="https://openstreetmap.org">OpenStreetMap</a>'
            }
          },
          layers: [{
              "id": "buildings",
              "source": "example_source",
              "source-layer": "landuse",
              "type": "fill",
              "paint": {
                "fill-color": "steelblue"
              }
            },
            {
              "id": "roads",
              "source": "example_source",
              "source-layer": "roads",
              "type": "line",
              "paint": {
                "line-color": "black"
              }
            },
            {
              "id": "mask",
              "source": "example_source",
              "source-layer": "mask",
              "type": "fill",
              "paint": {
                "fill-color": "white"
              }
            }
          ]
        }
      });
    })
  }

  
</script>

<main>
  <input type="file" name="" id="" bind:files={files} on:change={onFilesLoad}>
  <div id="map" bind:this={mapEl}>

  </div>
</main>

<style>
  
</style>
`

**Comment by bdon** [comment]
Do you see http range requests being created in the network console? it looks like it's attempting to parse the MVT protocol buffers but not succeeding.

**Comment by kauly** [comment]
I have a similar issue with Nextjs: `Uncaught Error: Unimplemented type: 3`. The tile is rendering without problem in the Pmtiles Viewer.

Two requests are being made and the pmtiles file is being served with the http-server npm package:

![image](https://user-images.githubusercontent.com/15254623/226086472-9ce03e9a-f4e6-4712-b52b-e1d3b2681c47.png)

![image](https://user-images.githubusercontent.com/15254623/226086483-6dfa98a0-3c76-47bd-b3ef-2ac48e0e77cc.png)

**Comment by kauly** [comment]
The error:

![image](https://user-images.githubusercontent.com/15254623/226087750-06ff4a38-11f7-4551-aea9-a5b2e4840def.png)

**Comment by kauly** [comment]
Ok last comment, I put the project in this repo

https://github.com/kauly/pmtiles-testing

**Comment by bdon** [comment]
How did you generate your archive? It has the metadata field for compression set to 0 (unknown), meaning the browser does not know to decompress the tiles. Please use https://github.com/felt/tippecanoe and specify a `.pmtiles` extension for the output

**Comment by kauly** [comment]
I tried so many things but I think that I end up using the python script. The origin is a shape file converted to geojson.

**Comment by kauly** [comment]
Ok I got a new error using tippecanoe
`Error: Wrong magic number for PMTiles archive`

![image](https://user-images.githubusercontent.com/15254623/226121497-fbe35ec2-602e-481f-bd45-d0ca6bc7fcf2.png)

**Comment by kauly** [comment]
I think that tippecanoe is ignoring the extension and generating a mbtile

![image](https://user-images.githubusercontent.com/15254623/226121606-32ed7fcd-ae37-444d-b823-f35b1c57b388.png)

**Comment by kauly** [comment]
yeah Im using a old version of tippecanoe

**Comment by kauly** [comment]
Now Im not getting errors but nothing is being rendered. I'm suspecting that the tile has no layers. Is this the right tippecanoe command:

`tippecanoe -z12 -o gfpolis.pmtiles --drop-densest-as-needed gfpolis.geojson`

**Comment by kauly** [comment]
I got it now, its just a polygon.

**Comment by bdon** [comment]
OK, thanks for the notes. Need to double check the issue with python writer here: https://github.com/protomaps/PMTiles/issues/139

**Comment by jamieodonnell** [comment]
> I got it now, its just a polygon. Thank you for the tippecanoe tip.

What was the issue in the end? Am having same issue. Comments from whoever was helping / solving seem to have disappeared.
