### ISSUE TITLE
PMTiles from OSMX database

### ISSUE THREAD

**Issue by thisisaaronland** [protomaps/PMTiles#12]
Am I correct in understanding that `.pmtiles` are derived from `.osmx` databases?

If that is the case is there public code/tooling to do the conversion? I've been poking around the various repos and documentation but can't seem to find it.

**Comment by bdon** [comment]
`osmx extract` will give you a .osm.pbf file that works the same way as the planet file, Geofabrik downloads, etc: https://protomaps.com/extracts

There is open source tooling like https://github.com/systemed/tilemaker to convert from PBF to MBTiles, and MBTiles to PMTiles can be performed with the python `pmtiles-convert` command.

**Comment by thisisaaronland** [comment]
Thanks, that makes sense. I've found a different hiccup in the process but filed a separate issue for that (https://github.com/protomaps/PMTiles/issues/13).
