### ISSUE TITLE
compatibility with tippecanoe v2.11.0 generator?

### ISSUE THREAD

**Issue by DavidDvpt** [protomaps/PMTiles#124]
hi,
we have a set of data generated by tippecanoe v1.36.0 and it work's fine, but we need to update ours datas.
With the new générator version (v2.11.0), tilesets seems to be ok, the layer is in the map but the tileset is transparent.
paint rules is not read
i use 1.23.0 version of protomaps.

my code
```
const p = new protomaps.PMTiles(pmtilesUrl4(inseeCode));
      p.getMetadata()
        .then(
          (m: any) => {
            console.log(m);
            const layer = protomaps.leafletLayer({
              paint_rules: [
                {
                  dataLayer: inseeCode,
                  symbolizer: new MyPaintSymbolizer(),
                  minzoom: 0,
                  maxzoom: 22,
                },
              ],
              label_rules: [
                {
                  dataLayer: inseeCode,
                  symbolizer: new MyLabelSymbolizer(),
                  minzoom: 18,
                  maxzoom: 22,
                },
              ],
              attribution: '',
              url: p.source.getKey(),
            });

            layer.options.id = 'cadastral';
            layer.options.zIndex = 2;
            console.log(layer);
            layer.addTo(map);
          },
          (err) => console.log('err', err)
        )
        .catch((err: any) => console.log(err));
```

paint rules : 

```
export class MyPaintSymbolizer {
  draw(context: any, geom: any, properties: any, attr: any) {
    const stroke = '#000';
    const width = 2;
    console.log(properties, attr);
    // if want to color buiding with another color
    // if (attr.props.is_parcel !== true) {
    //   stroke = '#f00';
    //   width = 6;
    // }

    context.fillStyle = 'transparent';
    context.strokeStyle = stroke;
    context.lineWidth = width;
    context.beginPath();

    for (const poly of geom) {
      for (let p = 0; p < poly.length; p++) {
        const pt = poly[p];
        if (p === 0) context.moveTo(pt.x, pt.y);
        else context.lineTo(pt.x, pt.y);
      }
    }

    context.stroke();
    context.fill();
  }
}
```

same for MyLabelSymbolizer
the console log into paint rules display datas with actual dataset but not with new generation 

anyone have same problem?

thx

**Comment by DavidDvpt** [comment]
the datas are present in p.getMetadata
json:"{\"vector_layers\": [ { \"id\": \"64102\", \"description\": \"\", \"minzoom\": 0, \"maxzoom\": 20, \"fields\": {\"is_parcel\": \"Boolean\", \"parcel_id\": \"String\"} } ],\"tilestats\": {\"layerCount\": 1,\"layers\": [{\"layer\": \"64102\",\"count\": 26095,\"geometry\": \"Polygon\",\"attributeCount\": 2,\"attributes\": [{\"attribute\": \"is_parcel\",\"count\": 2,\"type\": \"boolean\",\"values\": [false,true]},{\"attribute\": \"parcel_id\",\"count\": 1000,\"type\": \"string\",\"values\": [\"000AB0001\",\"000AB0002\",\"000AB0003\",\"000AB0004\",\"000AB0005\",\"000AB0006\",\"000AB0008\",\"000AB0013\",\"000AB0014\",\"000AB0019\",\"000AB0021\",\"000AB0023\",\"000AB0025\",\"000AB0028\",\"000AB0031\",\"000AB0034\",\"000AB0036\",\"000AB0037\",\"000AB0039\",\"000AB0040\",\"000AB0041\",\"000AB0042\",\"000AB0043\",\"000AB0048\",\"000AB0049\",\"000AB0051\",\"000AB0052\",\"000AB0053\",\"000AB0054\",\"000AB0055\",\"000AB0056\",\"000AB0057\",\"000AB0083\",\"000AB0084\",\"000AB0106\",\"000AB0108\",\"000AB0110\",\"000AB0111\",\"000AB0112\",\"000AB0113\",\"000AB0114\",\"000AB0117\",\"000AB0118\",\"000AB0130\",\"000AB0135\",\"000AB0136\",\"000AB0137\",\"000AB0138\",\"000AB0140\",\"000AB0141\",\"000AB0144\",\"000AB0146\",\"000AB0148\",\"000AB0150\",\"000AB0152\",\"000AB0154\",\"000AB0155\",\"000AB0156\",\"000AB0157\",\"000AB0158\",\"000AB0162\",\"000AB0163\",\"000AB0165\",\"000AB0167\",\"000AB0168\",\"000AB0169\",\"000AB0170\",\"000AB0171\",\"000AB0173\",\"000AB0174\",\"000AB0175\",\"000AB0176\",\"000AB0178\",\"000AB0179\",\"000AB0180\",\"000AB0183\",\"000AB0184\",\"000AB0185\",\"000AB0188\",\"000AB0189\",\"000AB0190\",\"000AB0191\",\"000AB0192\",\"000AB0193\",\"000AB0194\",\"000AB0195\",\"000AB0196\",\"000AB0197\",\"000AB0198\",\"000AB0199\",\"000AB0200\",\"000AB0201\",\"000AB0202\",\"000AB0207\",\"000AB0208\",\"000AB0213\",\"000AB0214\",\"000AB0215\",\"000AB0216\",\"000AB0217\"]}]}]}}"

**Comment by DavidDvpt** [comment]
here the two files
this one is ok and works in pmtiles viewer too
[https://tilesets.urbanease.io/64/64102/64102.pmtiles](https://tilesets.urbanease.io/64/64102/64102.pmtiles)

this one don't work with leaflet and PmTiles viewer
[https://tilesets.urbanease.io/2023-01-01/64/64102/64102.pmtiles](https://tilesets.urbanease.io/2023-01-01/64/64102/64102.pmtiles)

the metadata are ok but in the second paint_rules and label_rules don't work

**Comment by bdon** [comment]
The first file seems to be a pmtiles v2 file, it works for me in the viewer

The 2nd one has a valid v3 header, but it gets a protobuf decode error when reading the data. It looks like you are running tippecanoe and outputting MBTiles first. you can specify the output as `-o FILENAME.pmtiles`, can you try that with the latest version of tippecanoe at https://github.com/felt/tippecanoe ?

**Comment by DavidDvpt** [comment]
it works! it is fastest
