### ISSUE TITLE
Getting Error: Wrong magic number for PMTiles archive

### ISSUE THREAD

**Issue by tomeronen** [protomaps/PMTiles#126]
Hello i am getting the following error when trying to load a pmtiles file that was created using felt/tippecanoe.  

code:

```
import pmtiles from "pmtiles";

const p = new pmtiles.PMTiles('path to public storage with pmtiles');

p.getHeader().then((header) => {
    console.log(header);
}).catch((err) => {
    console.log(err);
});
```
did not find documentation on the meaning of this error, did somebody have a this experience or can give some insight on meaning of the error?

**Comment by tomeronen** [comment]
The start of the generated pm tiles is:

**Comment by tomeronen** [comment]
The problem in my case was a not updated tippecanoe version

**Comment by bdon** [comment]
you need to use source from https://github.com/felt/tippecanoe which is the actively developed version, and where 2.0+ starts.

**Comment by daisy12321** [comment]
Thank you Brandon, that worked
