### ISSUE TITLE
Update project URL to be main docs page?

### ISSUE THREAD

**Issue by jamesscottbrown** [protomaps/PMTiles#127]
The project URL listed in the sidebar on the right is currently that of the PMTiles Inspector ([protomaps.github.io/PMTiles/](https://protomaps.github.io/PMTiles/)).

Most readers would probably find a link to the main PMTiles docs ([https://protomaps.com/docs/pmtiles/](https://protomaps.com/docs/pmtiles/)) more useful.

**Comment by bdon** [comment]
Good catch, I've updated that. Thanks!
