### ISSUE TITLE
PMtiles in serverfull enviorment 

### ISSUE THREAD

**Issue by tomeronen** [protomaps/PMTiles#130]
Hello, i think a common use case might be adding PMtiles that is already 'serverfull'. This can bring a lot of benefits like using an existing servers:
1. Logging 
2. Metrics
3. Caching 
4. Error handling 

The move to PMtiles brings simplification to the server, and removes the need of loading MBtiles into disk. The server becomes really thin and does not need many resources. 

I am having a bit of a hard time implementing this. for example in Node.Js i was expecting that: 
```
const pmTilesFile = new pmtiles.PMTiles(URL_TO_PM_TILES);
const tileResponse = await pmTilesFile.getZxy(z, x, y);
const tileData = Buffer.from(tileResponse.data).toString('base64');
```

would bring the compressed pbf data that is in the tile that is in the x,y,z mapping. But it did not work. 
Does anyone else share this use case? 
Does someone has any insights to how it might be implemented?

**Comment by bdon** [comment]
that code looks more or less to me, what problem were you encountering?

**Comment by bdon** [comment]
We now have a "serverful" deployment option via the Caddy plugin:

https://docs.protomaps.com/deploy/server

Welcome to open new separate issues in http://github.com/protomaps/go-pmtiles or here about that or other languages.
