### ISSUE TITLE
Map is not appearing correct

### ISSUE THREAD

**Issue by sing78** [protomaps/PMTiles#133]
Hi,
I downloaded from Geofabrik in a .osm.pbf a country (Italy). Then i converted the .osm.pbf file to a .mbtiles file (using Tilemaker).Then I converted the .mbtile file to .pmtiles format (using pmtiles command).
Then,I used the http-server to view the pmtile file locally.However,what I see is this,which contains no data:

![Screenshot from 2023-03-11 19-56-07](https://user-images.githubusercontent.com/22524729/224504237-22d9c467-29da-46f7-84f9-65803b85ea45.png)

What I am doing wrong?
Thanks

**Comment by bdon** [comment]
Please see https://github.com/protomaps/basemaps/issues/15
