### ISSUE TITLE
Suggestion for CDN deployment documentation

### ISSUE THREAD

**Issue by hrecht** [protomaps/PMTiles#149]
Hi, thanks for the great work on Protomaps. I have a suggestion for a clarification on the AWS Cloudfront deployment page at https://protomaps.com/docs/cdn/aws.

It would be very helpful to specify how to access the newly hosted tiles in that document, perhaps right after https://protomaps.com/docs/cdn/aws#configuration.

The text could say something like:
On the Cloudfront distribution page, copy the "Distribution domain name" for your pmtiles distribution - this will look like https://AAA.cloudfront.net.
Your file can now be accessed at https://AAA.cloudfront.net/[PMTILESNAME]/{z}/{x}/{y}.mvt.

I had trouble figuring out how to specify the tile location in my map code - I think a little explanation like that could really help future users.

(Originally opened in the wrong repo as https://github.com/protomaps/protomaps.js/issues/109.)

**Comment by bdon** [comment]
I have updated the docs at https://protomaps.com/docs/cdn/aws#accessing-your-tiles - thanks!
