### ISSUE TITLE
Diagnose Cloudflare R2 performance issues related to range requests on large files

### ISSUE THREAD

**Issue by bdon** [protomaps/PMTiles#150]
See https://github.com/onthegomap/planetiler/discussions/533#discussioncomment-5451574

**Comment by AndrewJDR** [comment]
@bdon Just to clarify something here, are the range requests only slow when cloudflare CDN caching is being used in front of R2? Or are they also slow with direct requests to R2 without caching?

The reason I ask -- There's a very well known issue with R2 and CDN caching, which is that when a range request is made, cloudflare pulls the entire file into cache, THEN returns the range requested bytes to the client. They want to fix/improve this, but afaik they have not done so yet.

Therefore, if the cloudflare CDN cache is being used here, it could explain the slowdowns.

**Comment by bdon** [comment]
@AndrewJDR I am aware of that issue, but this is unrelated: this concerns fetching R2 ranges from within a Cloudflare Worker https://github.com/protomaps/PMTiles/blob/main/serverless/cloudflare/src/index.ts#L42 and not directly through the CDN.

The issue can be reproduced with R2 alone https://github.com/bdon/cloudflare-r2-latency as range requests will get slower for larger files.

**Comment by Frederik-Baetens** [comment]
Hi, an R2 release went out earlier this week which has drastically sped up ranged reads in very large files (should be noticeable on files of 10GB+, and significant on files of 100GB+). Performance should now be consistent independent of filesize.

**Comment by bdon** [comment]
@Frederik-Baetens thanks! marking this issue as resolved for now.
