### ISSUE TITLE
Release a newer version of python package

### ISSUE THREAD

**Issue by jtmiclat** [protomaps/PMTiles#157]
Hi!

I tried porting a v2 python server for pmtiles to v3 but when i used pip install pmtiles there were a few bugs in the latest version of pmtiles in pypi. 

The bugs themselves are a missing `import json` in `v2.py` and `reader.get(z,x,y)` returning a tile even if the tile doesnt exist.

The following [commit](https://github.com/protomaps/PMTiles/commit/681526a3706b141272e9c6b1114b7724322d7f56#diff-2e41c1d3db17f25c6d008720c3c0ed3f4080c401b3c89ff084b24bf10583021e) seems to address these issues already but pypi hasnt been updated. 

The quick and dirty solution was to install the package from github rather than pypi but I think pmtiles should publish a newer version to pypi

Thanks and appreciate your work!

**Comment by bdon** [comment]
Uploaded v3.1.1 https://pypi.org/project/pmtiles/3.1.1/ - can you confirm that it's resolved?

**Comment by jtmiclat** [comment]
@bdon Yup this addressed my issue. Thanks!
