### ISSUE TITLE
Additional documentation for pmtiles npm module?

### ISSUE THREAD

**Issue by spatialillusions** [protomaps/PMTiles#161]
The PMTiles Viewer sample uses for example import of the "FileAPISource", and that and a bunch of the other exports can't be found in any of the documentation. (Or maybe I'm just blind.)

Just wanted to check if there are any plans on expanding the documentation for the JS API, or if I just have to figure out things from samples and the code? If you don't have any plans on expanding the documentation I might try to make a pull, once I have figured out things. 

/Måns

**Comment by bdon** [comment]
Right now the samples and code are the best source; the documentation does deserve a standalone website once the developer-facing APIs are more settled. This would probably accompany a cleanup of the API in #96

**Comment by spatialillusions** [comment]
Thanks for your reply!
I think I can figure it out with some help from #118 
Great work with this library and PMTiles, and I'll see if I can help out writing some documentation once I feel that ai got the hang of it.
