### ISSUE TITLE
add react-map-gl documentation

### ISSUE THREAD

**Issue by tordans** [protomaps/PMTiles#163]
It would be great to have a dedicated example for how to add PMTiles to [ReactMapGL](https://github.com/visgl/react-map-gl).

I added some learnings at https://github.com/visgl/react-map-gl/discussions/2165 but there is some room for improvement.

In general, there are two things that make this example different from a regular Maplibre GL JS implementation: (a) until https://github.com/visgl/react-map-gl/issues/2161 is resolved, the main Types for ReactMapGL are Mapbox, which does not support `addProtocol`. (b) The component structure/pattern gives it a great native React feel but makes it a bit harder to find the right place to add the `addProtocol` so that React rendering cycles know about PMTiles at the right time.

**Comment by bdon** [comment]
There's some overlap with #155 here. I think a bit of extra docs related to react is worth it because of the unclear lifecycle and where `addProtocol` needs to happen, specific to MapLibre.

**Comment by bdon** [comment]
I'm going to close this for now - please reopen if you encounter other issues!

**Comment by bdon** [comment]
@tordans can you make that public?

**Comment by tordans** [comment]
>>https://codesandbox.io/p/sandbox/blissful-dewdney-cxdcx7?file=%2Fsrc%2FApp.js%3A9%2C1-10%2C1

> @tordans can you make that public?

Sorry. It should be public now.
