### ISSUE TITLE
js: adopt DecompressionStream

### ISSUE THREAD

**Issue by bdon** [protomaps/PMTiles#167]
`fflate` still needs to be used on Firefox, but Safari 16.4 supports this now: https://developer.mozilla.org/en-US/docs/Web/API/DecompressionStream

**Comment by 101arrowz** [comment]
You could try using this polyfill based on `fflate`: https://github.com/101arrowz/compression-streams-polyfill

**Comment by bdon** [comment]
@101arrowz thanks, this looks perfect! Opened up a draft at https://github.com/protomaps/PMTiles/pull/181

**Comment by bdon** [comment]
Version [`2.8.0-beta.0` is live on NPM](https://www.npmjs.com/package/pmtiles?activeTab=versions) which polyfills native `DecompressionStream` - this should reduce dropped frames on Chromium-based and Safari browsers.

**Comment by bdon** [comment]
Version 2.8.0 is on NPM.
