### ISSUE TITLE
feature: js: lazy loading

### ISSUE THREAD

**Issue by eddy-geek** [protomaps/PMTiles#17]
Currently the loading of the root directory is in the constructor.

This is not desirable when the layer is not the default one, eg when switching between several layers with leaflet [Layers Control](https://leafletjs.com/examples/layers-control/)s, the useless queries may be costly on backend side.

I guess we can start with `PMTiles().root ===undefined` and load it on first access (at the cost of initial load time)?

(There are also [leaflet layer control event](https://stackoverflow.com/questions/14103489/leaflet-layer-control-events) if needed)

**Comment by bdon** [comment]
Agreed, it seems wrong that initializing a PMTiles object will make a network request. Do you want to try a PR?
