### ISSUE TITLE
[python] reader requires opening file in write mode

### ISSUE THREAD

**Issue by geospatial-jeff** [protomaps/PMTiles#178]
👋 thanks for the great project!  This will raise a permission error:

```python
from pmtiles.reader import MmapSource, Reader

with open("test.pmtiles", "r") as f:  
    source = MmapSource(f) # This raises permission error.
    reader = Reader(source)
```

```
Traceback (most recent call last):
  File "/Users/jeff/Documents/repos/pmtiles-virtual-cog/testing.py", line 4, in <module>
    source = MmapSource(f) # This raises permission error.
             ^^^^^^^^^^^^^
  File "/Users/jeff/miniconda3/envs/pmtiles/lib/python3.11/site-packages/pmtiles/reader.py", line 15, in MmapSource
    mapping = mmap.mmap(f.fileno(), 0)
              ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied
```

If I open the file in read/write mode (either `r+` or `w+`). this code will work.  This is confusing because I'd expect the `Reader` class to only require read access to a file.  Assuming the reader is only doing read operations, this can be fixed by passing `mmap.mmap(access=mmap.ACCESS_READ)` to override the default read/write access used by `mmap`.

**Comment by bdon** [comment]
Thanks for the report, want to open a PR?

**Comment by geospatial-jeff** [comment]
Will do!
