### ISSUE TITLE
[python] header is deserialized multiple times on read

### ISSUE THREAD

**Issue by geospatial-jeff** [protomaps/PMTiles#179]
The `deserialize_header` function is called in multiple methods - `Reader.header`, `Reader.metadata`, and `Reader.get`.  Each `Reader` class is logically associated with a single pmtiles file, which means the header could be deserialized once and reused for the lifetime of the `Reader` instance.

It makes sense to me to cache the deserialized header as an instance attribute of the `Reader` class instead of deserializing it multiple times.  If this behavior is not desired then it makes sense to at least call `self.header()` from the `metadata` and `get` methods instead of repeating the call to `deserialize_header` (DRY).

**Comment by bdon** [comment]
What context are you accessing this in? The tough part of caching here, which exists in the JS client but not the Python one yet, is invaliding the cache if the file changed on disk or the remote HTTP ETag changed. The latter might be more useful for long-lived HTTP servers (and https://developmentseed.org/aiopmtiles/ might eventually be a better fit) but for one-off reading of a file I think adding an LRU cache here will be nice.

**Comment by geospatial-jeff** [comment]
> What context are you accessing this in?

My use case is a webserver where I wouldn't expect the underlying pmtiles to change and the `Reader` class is scoped to a single HTTP request.  I started writing my own code to get familiar with the spec but will likely use https://developmentseed.org/aiopmtiles/ (already talked to @vincentsarago about this a little).

> if the file changed on disk

I hadn't thought of this use case but its a great point.  I'm not super familiar with how python file handles / `mmap` behave when the underlying file changes.

> caching

Give the above, my personal take is that caching shouldn't be done by the python client.  I'm guessing most people who are using the python client are using it on the backend in which case the user should implement their own caching, for example a reverse HTTP proxy sitting between the python client and the pmtiles archive.

I always prefer caching at the deployment level, but it's easy enough to implement caching in the code using `lrucache` or equivalent (as `aiopmtiles` already does).

I will open a small PR to reduce some of the code duplication.

**Comment by bdon** [comment]
@geospatial-jeff there's some need for a short-lived cache to reduce the latency overhead of making multiple spatially correlated tile requests. The motivation here is to support applications that semi-frequently (daily-ish) re-upload a PMTiles archive with updated data but the same blob storage key. I'd guess it's low priority for on-disk uses but it would nice to have the logic be the same. In any case I do feel like `aiopmtiles` when matured will be a better fit for FastAPI programs, etc.
