### ISSUE TITLE
doc: correct js version to use

### ISSUE THREAD

**Issue by eddy-geek** [protomaps/PMTiles#18]
I just realized the version from the README: 
https://unpkg.com/pmtiles@0.0.4/pmtiles.js
is quite outdated compared with the version in the repo
https://github.com/protomaps/PMTiles/blob/master/js/index.src.mjs

For example it does not pass "options" to leaflet ie `return new cls()` instead of `return new cls(options)`.

Naively I tried https://unpkg.com/pmtiles@latest/pmtiles.js but it points to 0.3.1 which has different files so should be https://unpkg.com/browse/pmtiles@latest/index.js I guess?

**Comment by bdon** [comment]
Thanks, I've updated the README to point to the new version 1.0.0 instead as choosing `@latest` is usually a bad idea (there are backwards-compatible changes)
