### ISSUE TITLE
[python] `deserialize_header` should return pmtiles version

### ISSUE THREAD

**Issue by geospatial-jeff** [protomaps/PMTiles#180]
The method checks that the pmtiles archive is version 3 but doesn't return the version.  I think `deserialize_header` should transparently return all key/values in the header, it shouldn't be stripping out any information.

```python
{"version": buf[7]}
```

I'm happy to open a PR!

**Comment by bdon** [comment]
Yeah, a PR will be useful! There isn't any logic that actually depends on the version right now, but there could be in the future - it may be worth now adding an assertion that the python code is v3 only to ensure we're not reading a (not yet existing) v4+ file.

**Comment by geospatial-jeff** [comment]
Will open a PR!  Regardless of whether or not it is used I think it is useful to have.  As someone new to PMtiles and less familiar with the versioning history the first thing I wanted to check after creating an archive was the PMtiles version and that is currently not easily accessible through the python bindings.

>  it may be worth now adding an assertion that the python code is v3
This assertion already exists! https://github.com/protomaps/PMTiles/blob/main/python/pmtiles/tile.py#L207-L208
