### ISSUE TITLE
Hash function collisions / hash width for tile deduplication

### ISSUE THREAD

**Issue by bdon** [protomaps/PMTiles#20]
(edited as summary) The current Python `pmtiles-convert` program deduplicates by hashing each using the `hash` builtin: https://docs.python.org/3/library/functions.html#hash which produces a 64-bit value on 64-bit systems.

A typical basemap use case has about **40 million unique tile** contents for zooms 0-14; zoom 15 has 100-200 million unique tile contents.

See this on [Hash Collision Probabilities](https://people.cs.clemson.edu/~jmarty/courses/commonCourseContent/AdvancedModule-SecurityConceptsAndApplicationToLinux/HashCollisionProbabilities.pdf) for formulas. 

A collision between two hash values is unacceptable because that means the PMTiles archive will replace the collided tile with the wrong contents. 

The approximate "birthday paradox" probability of a collision giving a (perfectly distributed) hash function of possible values `n` where there are `k` values being hashed is: `k^2 / 2n`. 

* For 64-bit hashes and 40 million unique tiles, the probability of a collision is **~1 in 23,000**
* For 64-bit hashes and 200 million unique tiles, the probability is **~1 in 922**

The probability of collisions in these cases is unacceptably high for the general use case of 100m+ tiles. **A general-purpose deduplication implementation should use 128 bit hashes.**

* For 128-bit hashes and 40 million unique tiles, the probability of a collision is **1 in 4.25 * 10^21**
* For 128-bit hashes and 200 million unique tiles, the probability is **1.70 * 10^20**

**Comment by bdon** [comment]
Test script to find fnv1a collisions:

```golang
package main

import (
	"bytes"
	"hash/fnv"
	"log"
	"os"
	"zombiezen.com/go/sqlite"
)

func main() {
	conn, err := sqlite.OpenConn(os.Args[1], sqlite.OpenReadOnly)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	hsh_to_len := make(map[uint64]int)

	{
		stmt, _, err := conn.PrepareTransient("SELECT tile_data FROM tiles")
		if err != nil {
			log.Fatal(err)
		}
		defer stmt.Finalize()

		for {
			row, err := stmt.Step()
			if err != nil {
				log.Fatal(err)
			}
			if !row {
				break
			}
			reader := stmt.ColumnReader(1)

			buf := new(bytes.Buffer)
			buf.ReadFrom(reader)
			data := buf.Bytes()

			hsh := fnv.New64a()
			hsh.Write(data)
			sum := hsh.Sum64()

			if val, ok := hsh_to_len[sum]; ok {
				if val != len(data) {
					log.Fatal("error, length mismatch", sum, val, len(data))
				}
			} else {
				hsh_to_len[sum] = len(data)
			}
		}
	}
}
```

**Comment by bdon** [comment]
Running the deduplication check over a big archive with 64 bit fnv1a takes 9 minutes; with 128 bit fnv1a it takes 14 minutes.

Memory costs double of course

**Comment by nyurik** [comment]
would it make sense to compare hash + length, and treat that as a unique-enough content?

**Comment by bdon** [comment]
@nyurik you will need 32 bits for the length, so that's not that different from just using a 96 bit hash; in practice not much different than 128
