### ISSUE TITLE
CORS Policy

### ISSUE THREAD

**Issue by NazCodeland** [protomaps/PMTiles#223]
Hey, I've followed the instructions here: https://protomaps.com/docs/cdn/cloudflare#configuration

My R2 bucket is up and I am able to download a tile when I go to https://subdomain.barbercate.ca/canadamap/canada/0/0/0.mvt, however, when I try to access that same URL from code, I am getting `'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin'`

Through the Cloudflare dashboard I've set my environment variable `ALLOWED_ORIGINS` to `*` but it seems like it's not picking it up because I am still getting the CORS blocked message.

**Comment by bdon** [comment]
You are deploying through Wrangler but using the dashboard? Can you verify that the `ALLOWED_ORIGINS` environment variable is not being overwritten? Cloudflare recommends setting the env var in wrangler.toml, not the dashboard, otherwise one method can overwrite the other.

**Comment by NazCodeland** [comment]
I was using the dashboard for everything. I deleted the worker and created a new worker through the Wrangler CLI, added ```
[vars]
ALLOWED_ORIGINS = ""
``` to my `wrangler.toml` file. When I deploy my worker, the CLI shows me ```
 w deploy
 ⛅️ wrangler 3.3.0
------------------
Your worker has access to the following bindings:
- Vars:
  - ALLOWED_ORIGINS: "http://localhost:8080"
Total Upload: 41.69 KiB / gzip: 11.93 KiB
Uploaded map (1.10 sec)
Published map (0.30 sec)
  https://map.barbercateapp.workers.dev
Current Deployment ID: a51f699e-4f45-4fb1-a083-015396d30602
````
But when I go to `localhost:8080` in the console I am getting `Access to fetch at 'https://map.barbercate.ca/canada/%7Bz%7D/%7Bx%7D/%7By%7D.mvt' from origin 'http://localhost:8080'`


The code for that page is ```ts
//svelte project
<script lang="ts">
	import { onMount } from 'svelte';
	import maplibregl from 'maplibre-gl';
	import * as pmtiles from 'pmtiles';
	let mapContainer: HTMLElement;

	onMount(() => {
		// Modify the pmtiles library to include an Authorization header with a bearer token

		// add the PMTiles plugin to the maplibregl global.
		let protocol = new pmtiles.Protocol();
		maplibregl.addProtocol('pmtiles', protocol.tile);

		let PMTILES_URL = 'https://map.barbercate.ca/canada/{z}/{x}/{y}.mvt';
		const p = new pmtiles.PMTiles(PMTILES_URL);

		// this is so we share one instance across the JS code and the map renderer
		protocol.add(p);

		// we first fetch the header so we can get the center lon, lat of the map.
		p.getHeader().then((h) => {
			const map = new maplibregl.Map({
				container: mapContainer,
				zoom: 8,
				center: [-79.347015, 43.65107],
				style: {
					version: 8,
					glyphs: 'https://demotiles.maplibre.org/font/{fontstack}/{range}.pbf',
					sources: {
						openmaptiles: {
							type: 'vector',
							tiles: [PMTILES_URL],
							attribution: '© <a href="https://openstreetmap.org">OpenStreetMap</a>'
						}
					},
					layers: [...
					```

**Comment by NazCodeland** [comment]
I tried doing some digging, I created a `tail` for my worker. The logs showed `✘ [ERROR]   TypeError: Cannot read properties of undefined (reading 'get')`

I found out that the invocation to `getHeader()` is causing the error.
```ts
let v = await w.getHeader();
```

inside of `getHeader()`
```ts
async getHeader() {
  console.log(this.cache.getHeader) //  async getHeader(e, r) { ... }
  return await this.cache.getHeader(this.source);
}
```
the `this.source` for me is an object that contains another object of this shape; 
```ts
{
  "env": {
    "ALLOWED_ORIGINS": "*"
  },
  "archive_name": "canada"
}```

**Comment by NazCodeland** [comment]
Okay, so, somehow, I was over-riding the BUCKET var. At the beginning you said, "Can you verify that the ALLOWED_ORIGINS environment variable is not being overwritten?" I should have thought of also checking the BUCKET var. Well, I am glad I got it sorted. Thank you for the help @bdon

**Comment by bdon** [comment]
Thanks for the info!
