### ISSUE TITLE
Detect when tiles finished loading at current zoom level

### ISSUE THREAD

**Issue by gio0v** [protomaps/PMTiles#226]
Using Maplibre with PMTiles, is there a way to detect when, after a given zoom level change, the PMTiles tiles finished loading? It would be of tremendous help for my application if there was a `pmtiles` command or a clear way of listening to such an event.

**Comment by bdon** [comment]
In general that functionality isn't going to be specific to PMTiles; if what you want to do is know when the map is "loaded", you should listen to the `idle` event in MapLibre, which will fire not only after data tiles have loaded but also fonts and sprites.

**Comment by bdon** [comment]
I think this issue can be resolved since the desired functionality is part of MapLibre and not PMTiles specifically.
