### ISSUE TITLE
Docs: MapLibre demo broken with 404

### ISSUE THREAD

**Issue by graue** [protomaps/PMTiles#230]
Hi, thanks for making Protomaps!

Just letting you know [the MapLibre demo](https://protomaps.github.io/PMTiles/examples/maplibre.html) is not working, with a 404 error for the URL it's loading PMTiles JS from.

**Comment by bdon** [comment]
Thanks, it should be fixed now https://protomaps.github.io/PMTiles/examples/maplibre.html
