### ISSUE TITLE
GetObjectCommand for S3 may need endpoint to work for storage outside us-east-1

### ISSUE THREAD

**Issue by migurski** [protomaps/PMTiles#237]
I am seeing this error when attempting to use the AWS serverless implementation of PMTiles against a bucket that’s in US-East-1 from a Lambda that’s in US-West-2:

    "The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."

I tested an identical deployment in the US-East-1 region and the error does not appear.

Looking at [the S3 client implementation](https://github.com/aws/aws-sdk-js-v3/blob/0a6131e16a8a6578686679704d0da63805b632a7/clients/client-s3/src/commands/GetObjectCommand.ts#L360-L373), I see that PMTiles [provides a Bucket argument but not an Endpoint argument](https://github.com/protomaps/PMTiles/blob/main/serverless/aws/src/index.ts#L59-L63). Can we add support for a new `ENDPOINT` environment variable alongside `BUCKET` to correctly pass [additional endpoints](https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_region) like `s3.us-east-1.amazonaws.com`?

#### Complete Error

```
{
    "errorType": "PermanentRedirect",
    "errorMessage": "The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.",
    "name": "PermanentRedirect",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 301,
        "extendedRequestId": "07xLtjuLlUvRzu1vtrlPy8qSqdHAiMrzY2g0yzqZc0wwhmBx/c+Jai3l98uUFvJv8HKFf2lF6v+NXJva9c4GRw==",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "Code": "PermanentRedirect",
    "Endpoint": "s3.amazonaws.com",
    "Bucket": "felt-basemap-pmtiles",
    "RequestId": "117K6R4VWC84VW83",
    "HostId": "07xLtjuLlUvRzu1vtrlPy8qSqdHAiMrzY2g0yzqZc0wwhmBx/c+Jai3l98uUFvJv8HKFf2lF6v+NXJva9c4GRw==",
    "message": "The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.",
    "stack": [
        "PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.",
        "    at throwDefaultError (/var/runtime/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)",
        "    at deserializeAws_restXmlGetObjectCommandError (/var/runtime/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4356:51)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24",
        "    at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20",
        "    at async StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)",
        "    at async /var/runtime/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:56:20",
        "    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22",
        "    at async S3Source.getBytes (file:///var/task/index.mjs:2429:18)",
        "    at async getHeaderAndRoot (file:///var/task/index.mjs:2039:16)"
    ]
}
```

**Comment by bdon** [comment]
This is by design, because there isn't a strong reason to have the lambda and bucket in different regions.

If your bucket lives in `us-east-1`, the lambda should live in `us-east-1` as well. Given that many operations require more than one roundtrip the effect on latency will be huge if they are not colocated. 

If there is a compelling reason to do this we can add an `ENDPOINT` like above but this will be de-emphasized in any docs in favor of colocating the storage/compute.

Finally, if what you are trying to accomplish is multi-region distribution of storage that will require Lambda@Edge, which is a potential enhancement I'm open to, but Lambda@Edge must be configured in code ("hardcoded") and cannot use environment variables.

**Comment by migurski** [comment]
Okay, we can move our buckets around to compensate, thanks!
