### ISSUE TITLE
JavaScript API needs method to retrieve TileJSON

### ISSUE THREAD

**Issue by bdon** [protomaps/PMTiles#239]
since this is used internally by the MapLibre adapter, we can expose TileJSON, though should it include metadata like `vector_layers`? 

Requested by @JinIgarashi

**Comment by JinIgarashi** [comment]
Thank you for creating the issue. Yes, I think it would be useful if tilejson includes metadata like vector_layers and tilestats (if available).

**Comment by bdon** [comment]
This is added in 3.1.0:

https://pmtiles.io/typedoc/classes/PMTiles.html#getTileJson
