### ISSUE TITLE
Standalone viewer

### ISSUE THREAD

**Issue by ymoisan** [protomaps/PMTiles#244]
Hi.  Thank you for writing PMTiles!  I have uploaded a pmtile file on a bucket of ours that is behind a firewall so I can't load the url in the viewer.  Would you consider making the PMTiles viewer as a standalone package/container ?

Cheers!

**Comment by bdon** [comment]
* The viewer already is 100% client side, meaning if you can access protomaps.github.io on your computer and your firewall HTTP bucket, it should work.
* If you need to use the viewer without access to `protomaps.github.io` then you can run `npx vite build` in `app/` to create the static files in `app/dist`

**Comment by ymoisan** [comment]
In order to build I had to edit `vite.config.js` to add
``` javascript
rollupOptions: {
      external: ['fflate'], // Add 'fflate' here
    },
```
In `defineConfig`.

Using the resulting js bundle still leads to issues with `fflate`.  I'll post here when I have them solved.  

We're also working on CORS on the server side, which happens to be a NooBaa "website" bucket (in OpenShift) that apparently won't let one set CORS.

Thanx !

**Comment by bdon** [comment]
To build the viewer you need to go into the `/js` directory and do a `npm install`, since the `/app` folder depends on the module in the sibling folder. I will add this to the instructions

**Comment by bdon** [comment]
added app/README.md

**Comment by ymoisan** [comment]
For completeness, I had to edit the generated `index.html` the default location of which is .../app/dist/assets to point to current_dir, that is, put a period before slash as in : 
```HTML
<script type="module" crossorigin src="./assets/index.a27cc9f6.js"></script>
<link rel="stylesheet" href="./assets/index.1291385f.css">
```
Everything worked well after that.

Thanx gain !
