### ISSUE TITLE
Can I use this (hosted Protomaps) to server .png images React Native Maps)

### ISSUE THREAD

**Issue by theobouwman** [protomaps/PMTiles#253]
Hi,

We are using `react-native-maps` and want to use hosted Protomaps for our Android version, Google Maps is too expensive.

Their code required `.png`s to be served: https://github.com/react-native-maps/react-native-maps#using-a-custom-tile-overlay

Is this also possible with the hosted Protomaps API?

Thanks

**Comment by bdon** [comment]
No, the Protomaps system right now is focused only on delivering vector tiles.

If you're looking for an affordable raster (.png) tiles service I recommend https://www.thunderforest.com
