### ISSUE TITLE
maxzoom argument error

### ISSUE THREAD

**Issue by YingZhaoSF** [protomaps/PMTiles#254]
Hi,

I am using "pmtiles-convert --maxzoom 12 --overwrite input_file output_file" to convert a mbtiles file to pmtiles. 

I keep running into the error "File "/opt/homebrew/bin/pmtiles-convert", line 34, in <module>
    mbtiles_to_pmtiles(args.input, args.output, args.maxzoom)
  File "/opt/homebrew/lib/python3.11/site-packages/pmtiles/convert.py", line 87, in mbtiles_to_pmtiles
    pmtiles_header, pmtiles_metadata = mbtiles_to_header_json(mbtiles_metadata)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pmtiles/convert.py", line 14, in mbtiles_to_header_json
    header["min_zoom"] = int(mbtiles_metadata["minzoom"])".

But minzoom is not an argument for this command. Would you help on this error?  Thank you!

**Comment by bdon** [comment]
Does your mbtiles metadata have a `minzoom` key?

For converting from mbtiles you should use https://github.com/protomaps/go-pmtiles

**Comment by bdon** [comment]
Please use the `go-pmtiles` cli for this instead.
