### ISSUE TITLE
OpenLayers implementation

### ISSUE THREAD

**Issue by lysek** [protomaps/PMTiles#265]
I am working on a mapping app and I wanted to add support for pmtiles as a possible source of raster tiles. We do not want to use WebGL for the rendering because we had some display issues on some older mobile devices.

I have implemented this OpenLayers source which can load PMTiles into classic [TileLayer](https://openlayers.org/en/latest/apidoc/module-ol_layer_Tile-TileLayer.html), not just [WegGLTile](https://openlayers.org/en/latest/apidoc/module-ol_layer_WebGLTile-WebGLTileLayer.html) layer. [DataTile](https://openlayers.org/en/latest/apidoc/module-ol_source_DataTile-DataTileSource.html) source is not compatible with other than GL layer.

Feel free to use it in [ol-pmtiles](https://www.npmjs.com/package/ol-pmtiles) package or just as an example for others.

``` javascript
import TileState from 'ol/TileState';
import XYZ from 'ol/source/XYZ';

export class PMTilesImageSource extends XYZ {

    constructor(source, options) {
        delete options.url;
        delete options.urls;
        delete options.tileUrlFunction;

        super({
            ...options,
            //has to be something
            url: '{x}/{y}/{z}',
            tileLoadFunction: (imageTile) => {
                imageTile.setState(TileState.LOADING);
                var [z, x, y] = imageTile.getTileCoord();
                this._pmtiles.getZxy(z, x, y).then(response => {
                    imageTile.getImage().addEventListener('load', () => {
                        imageTile.setState(TileState.LOADED);
                    });
                    imageTile.getImage().addEventListener('error', () => {
                        imageTile.setState(TileState.ERROR);
                    });
                    imageTile.getImage().src = URL.createObjectURL(new Blob([response.data]));
                }).catch(() => {
                    imageTile.setState(TileState.EMPTY);
                });
            }
        });
        this.setState('loading');

        this._pmtiles = new pmtiles.PMTiles(source);
        this._pmtiles.getHeader().then((h) => {
            this.tileGrid.minZoom = h.minZoom;
            this.tileGrid.maxZoom = h.maxZoom;
            this.setState('ready');
        });
    }

}
```

You can also use the `var [z, x, y] = imageTile.getTileCoord();` in your `PMTilesVectorSource` class inside the `tileLoadFunction` instead of parsing the URL string.

**Comment by bdon** [comment]
@lysek what were the specific display issues related to WebGL? That would be helpful for users to decide which implementation use. Thanks for the example!

**Comment by lysek** [comment]
We experienced two different issues on Samsung mobile devices with Chrome and Android 4.x (our customer still uses these), the app displays multiple layers, not just background tiles:
- map went black, other HTML GUI was OK
- the whole display started to scatter (rectangles of image moved anywhere, including HTML GUI)

We were not sure what was the exact cause, but it seems that it was related to memory because OL uses multiple canvas elements when you mix different types of layers (tiles/GLtiles/vector/vectorimage) - it displays them layered. On the other hand if you stick with less layer types, it paints into less canvas elements or it somehow merges them. When you rotate the map, the canvas gets even bigger to cover required area - we decided to disable map rotation and use just classic non-gl TileLayer + (VectorImageLayer)[https://openlayers.org/en/latest/apidoc/module-ol_layer_VectorImage-VectorImageLayer.html] for overlay graphics and display issues were gone.

This is a kind of edge use-case, nevertheless some developers might prefer to stay away from webgl to avoid issues on older systems.

Our idea with PMTiles is to use it as optional offline map for PWA version of our product.

Thanks for PMTiles.

**Comment by prusswan** [comment]
Not sure if this is the same reason, but I have tried comparing the pmtiles version with the regular version of OSM raster. I believe the tile converter does not modify the raster tile content, but the WebGL + PMTilesRasterSource version just seems more blurry and less smoothing (especially for text labels) when zoomed out. It is important (at least for me) for PMtiles to be able to render the raster content in the same manner, so that this would not be seen as a regression attributed to PMtiles.

**Comment by bdon** [comment]
Can you post an interactive example of the WebGL with PMTilesRasterSource with OSM Carto tiles? It may be that the WebGL OpenLayers implementation is using different resampling for images. In any case it is unlikely that it is related to the PMTiles module.

**Comment by bdon** [comment]
If you want to display raster tiles without blurriness like in that CSB example you need to disable fractional zooms like Leaflet does by default. Any fractional zooming level with raster tiles will need to be upsampled in between whole integer zooms.

**Comment by bdon** [comment]
Basic implementation is done already.
