### ISSUE TITLE
Displaying only a subset of the features!

### ISSUE THREAD

**Issue by MarcCoquand** [protomaps/PMTiles#274]
Hi!

Thanks for all the hard work. I am trying to understand if there is a way to only use a subset of the features it comes with? In my case, I only need access to water, land and borders, not any label or anything more. Is it possible to compile with only those features?

**Comment by bdon** [comment]
What dataset are you using, and what renderer? For MapLibre you can customize a style JSON to show just what you need. Or you can change your tileset generation to leave off some layers.

**Comment by district10** [comment]
@bdon I noticed that PMTiles can have `0x01 | MVT Vector Tile`s, so it's possible to just use Mapbox/MapLibre style expression to customize view (like you just mentioned).

Can we add url query param `style_override_url=some_styling_url` to <https://protomaps.github.io/PMTiles/>?

That would be awesome.

**Comment by bdon** [comment]
If you want to use a custom JSON style you should write your own application instead of using the viewer. The viewer is only designed to preview any archive and doesn't have a customizable style.

**Comment by bdon** [comment]
Closing as this is out of scope of the PMTiles container format itself, please refer to MapLibre or other renderer Style JSON for accomplishing this.
