### ISSUE TITLE
Show tile size of the loaded dataset in the Viewer

### ISSUE THREAD

**Issue by dabreegster** [protomaps/PMTiles#280]
![Screenshot from 2023-10-28 10-37-24](https://github.com/protomaps/PMTiles/assets/1664407/29081d93-7129-4b5a-84bd-2896ebfe9ac2)
The size shown is of the basemap tiles, not the file loaded. That size is available in the Inspector tab -- though maybe some spacing between the columns would be helpful
![Screenshot from 2023-10-28 10-39-17](https://github.com/protomaps/PMTiles/assets/1664407/afd331c6-6bce-41f9-95dc-92fb8560497b)

If the purpose of the Viewer is to debug pmtiles files generated, could the size shown be of the file? Or show both, or have an option?

I'd be happy to have a stab at this, except I can't actually figure out where the checkbox gets referenced anywhere in the code besides https://github.com/protomaps/PMTiles/blob/f2805a16814fb8772a8d4069bcdcd365981bc499/app/src/MaplibreMap.tsx#L344

**Comment by bdon** [comment]
Duplicate of https://github.com/protomaps/PMTiles/issues/122

The text drawn in the corner of the tile is part of MapLibre and it does not expose any hooks to customize or hide/show that size view.

**Comment by dabreegster** [comment]
Ah thanks, indeed confusing.
