### ISSUE TITLE
Is there a way to use PMtiles without Node or CDN?

### ISSUE THREAD

**Issue by nuclearsecrecy** [protomaps/PMTiles#296]
My site is built in native JS and not Node, so porting it into a Node environment would be a huge undertaking. 

Currently I have it deployed to a Cloudflare CDN but I am a little concerned that the number of Workers needed is going to potentially cost money. (Currently it is over 100 per user, and I get about 15-20K users per day, so that adds up.) 

Is there an easy drop-in way to use pmtiles in my existing code without using Node or a CDN? I am using Maplibre to render the map.

**Comment by nuclearsecrecy** [comment]
OK, I figured it out — [this page](https://github.com/protomaps/PMTiles/blob/main/js/examples/maplibre.html) gives an example of how to do this. I have other issues getting it to work, but that will be for a separate post!

**Comment by bdon** [comment]
Yes, you use maplibre addProtocol which is just an es6 module for the browser. https://docs.protomaps.com/pmtiles/maplibre

> the number of Workers needed is going to potentially cost money

Yes, workers always cost money, but the unit prices are low - a site that serves 20k users per day I'd guess would cost between $10-50 a month on a cloudflare bill

**Comment by bdon** [comment]
>  if I turned on caching for .pmtiles files, it did not work — the tiles failed to download correctly

Correct, the "free" Cloudflare CDN does not cache Range (206) responses by design.

> Cloudflare pricing on the PMTiles site has an important error in it.

Yes, let me fix that. The docs are out of date since all the pricing should move to the "Standard" instead of the Bundled pricing model, which should indeed be cheaper. 

Those costs for the traffic look in line with my expectations.
