### ISSUE TITLE
PMTiles js example

### ISSUE THREAD

**Issue by humanitiesNerd** [protomaps/PMTiles#302]
I tried with [this](https://github.com/protomaps/PMTiles/blob/main/js/examples/maplibre.html) example and it worked

 Then I changed i slightly and it doesn't work anymore

in the dev tools, if I hover on the div with the cursor the preview does show up and it seems correct !

But in the browser window nothing is shown :-/

This is a screenshot 
![pmtile con le strade](https://github.com/protomaps/PMTiles/assets/283791/6e71e1f4-86de-4fff-85bd-0aef479c821b)

And [this](https://codeberg.org/abbienormal/protomaps) is my repository

**Comment by bdon** [comment]
Did you resolve the problem?

**Comment by humanitiesNerd** [comment]
yes, I did solve the problem

The problem was that I was lacking a few directives in the stylesheet

These

```
.maplibregl-map {
  width: auto;
  height: 600px;
}


fixed the issue 
```
