### ISSUE TITLE
Error: Invalid tile URL. Having trouble getting AWS/cloudfront/lambda pmtiles working.

### ISSUE THREAD

**Issue by uptickmetachu** [protomaps/PMTiles#318]
This project looks very promising but I'm running into a problem when deploying OSM pmtiles to AWS (cloudfront + lambda function url).

I'm getting response with the error message `Invalid tile URL` when using the pmtiles viewer.

The url I've tried is "https://REDACTED/latest.pmtiles". The file is stored in s3 as `latest.pmtiles`. 

Environment variables:
- I've only set the `BUCKET`  and `PUBLIC_HOSTNAME` 
- I haven't touched `PMTILES_PATH`.

I'm able to view `/latest.json` and `/latest/0/0/0.mvt` but specifying `/latest.pmtiles` with the viewer returns the above error.

Looking through the source at https://github.com/protomaps/PMTiles/blob/main/serverless/aws/src/index.ts I can't see where pmtiles is ever going to return a valid response for `/latest.pmtiles` as it doesn't fit either https://github.com/protomaps/PMTiles/blob/d301b64ad5f366bdeceabe047e0d778257b0b0fe/serverless/shared/index.ts#L10-13 regexes.

**Comment by uptickmetachu** [comment]
I'm an idiot.

This is for serving pmtiles directly from s3 vs serving it via /z/y/x format.

**Comment by bdon** [comment]
Yeah, once you're serving Z/X/Y it's assumed you want the advantages of doing it that way as opposed to raw .pmtiles directly from S3. Is there a docs improvement you can suggest to clarify this?

**Comment by uptickmetachu** [comment]
I'm a relative newbie to mapbox and mapping formats so it wasn't immediately obvious to me where I was going wrong.

After deploying the serveless components via the web viewerhttps://protomaps.github.io/PMTiles/. Due to my unfamiliarity; it didn't click to me that the viewer was specific to the pmtiles format (and that the z/y/x format was not pmtiles specific). 

This was further reinforced when I went to the react sample code which only contained samples that used the protomap protocol. 

So possible suggestions (based on my confusion):
1.  an additional react example with `z/y/x` format and without the protomap protocol
2. enhancing the webviewer to work with the TileJson url.

**Comment by bdon** [comment]
2) will be addressed when I next get a chance to improve the viewer in https://github.com/protomaps/PMTiles/issues/49

**Comment by wcedmisten** [comment]
:warning: Just for my own sanity when I inevitably hit this issue again (and also anyone else it may help):

The source object in MapLibreGL has to follow a very specific format in order to work with the Protomaps R2 adapter.

```
    "sources": {
          "openmaptiles": {
            "type": "vector",
            "tiles": ["https://virginia-tiles.wcedmisten.dev/virginia-2024-07-06/{z}/{x}/{y}.mvt"]
          }
```

The extension `.mvt` is required as well as the prefix before the `/{z}/{x}/{y}` section.

Another thing that caught me was this field is called `tiles` for the MVT format and not `url` like the pmtiles extension uses.

**Comment by bdon** [comment]
@wcedmisten All the serverless adapters and go-pmtiles also support TileJSON:

```
"url": "https://virginia-tiles.wcedmisten.dev/virginia-2024-07-06.json"
```

That does add the overhead of one intermediate request, though. Perhaps we should converge on all docs using TileJSON though for consistency? 

The `tiles:[]` is annoying and mostly an artifact of how people used multiple subdomains, and also doesn't set `maxzoom` automatically.

**Comment by wcedmisten** [comment]
Thanks Brandon, that worked! I think I was using the wrong URL for the `.json` ending, but that one works for me!

**Comment by bdon** [comment]
Updating docs: https://github.com/protomaps/docs/pull/46
