### ISSUE TITLE
Detect pmtiles file change in javascript client

### ISSUE THREAD

**Issue by cquest** [protomaps/PMTiles#326]
When the pmtile file is updated on the server with a new one with the same URL, the js client does not detect the change and queries ranges based on cached data that are not valid anymore.

A check on each range reponse on etag or last-modified could detect such a change and empty the cache.

**Comment by bdon** [comment]
The JavaScript client already behaves this way. https://github.com/protomaps/PMTiles/blob/main/js/index.ts#L544

Do you have a report of this not working on your S3-like storage?

The current implementation is not 100% bulletproof because inspecting ETags in responses is not good enough, only `If-Match` is 100% correct to avoid 416 Range not Satisfiable responses.

**Comment by cquest** [comment]
Thanks for this fast answer :)

I did encountered a problem yesterday when I switched my pmtiles file on my server without reloading the page on which the map was displayed with MapLibre. I verified that Etags and last-modified when different before and after the switch.
I'm not using S3, but a plain nginx to serve the pmtiles file ranges directly.

I've just checked the request again and there is no if-match header send in the query (tested with Firefox 121 on Ubuntu).
The test map is here: https://files.pavie.info/clients/panoramax/pmtiles/

When Etag changes, it is detected but the index cache is not invalidated and reloaded (as well as the requested tile range), breaking the map for any further tile request.

**Comment by bdon** [comment]
Like I wrote above, the client does not currently send an `If-Match` header. That will require a major version revision of the JavaScript library which isn't on the timeline right now. #90 

When the ETag changes the cache should already be invalidated, the specific case where this approach does not work is if your archive shrunk and you request bytes past the end of the new file, in which case a HTTP 416 is returned.
