### ISSUE TITLE
Error `Could not find a declaration file for module 'pmtiles'. '…node_modules/pmtiles/dist/index.mjs' implicitly has an 'any' type.`

### ISSUE THREAD

**Issue by tordans** [protomaps/PMTiles#347]
This is a follow up to https://github.com/protomaps/PMTiles/issues/248 and https://github.com/protomaps/PMTiles/issues/317

This is a demo repo: https://github.com/tordans/berlin-bikenetwork-monitoring/pull/4 which uses `import { Protocol } from 'pmtiles'`

> Could not find a declaration file for module 'pmtiles'. '/berlin-bikenetwork-monitoring/node_modules/pmtiles/dist/index.mjs' implicitly has an 'any' type.
>  There are types at '/berlin-bikenetwork-monitoring/node_modules/pmtiles/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'pmtiles' library may need to update its package.json or typings.ts(7016)

---

The work around `import * as pmtiles from 'pmtiles'` does not work anymore either.

> Could not find a declaration file for module 'pmtiles'. '/berlin-bikenetwork-monitoring/node_modules/pmtiles/dist/index.mjs' implicitly has an 'any' type.
>  There are types at '/berlin-bikenetwork-monitoring/node_modules/pmtiles/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'pmtiles' library may need to update its package.json or typings.ts(7016)

**Comment by bdon** [comment]
I have your branch checked out, how to I reproduce that error message?

**Comment by tordans** [comment]
> I have your branch checked out, how to I reproduce that error message?

The message is from hovering in VS Code. But 'npm run build' should fail as should 'npm run type-check'

**Comment by bdon** [comment]
> astro@0.0.1 type-check
> tsc --noEmit --skipLibCheck

does not emit an error.

**Comment by bdon** [comment]
can you please try 3.0.2:

passes publint: https://publint.dev/pmtiles@3.0.2

**Comment by tordans** [comment]
@bdon awesome, this solved my issues on Vite / Astro. Will test a NextJS app soon.

**Comment by tordans** [comment]
Update FYI: I also [checked](https://github.com/FixMyBerlin/atlas-app/commit/4726ce9896fa57678b47bfc277103cdcfe839dee) NextJS and it looks like that works great as well. I don't have a `require` project at hand to test that.

**Comment by bdon** [comment]
Dual-ESM and CommonJS projects seem to be discouraged now, so `require` projects won't be able to load PMTiles 3.x by default without an extra transpilation step.
