### ISSUE TITLE
How to use PMTiles with Mapbox

### ISSUE THREAD

**Issue by Mtehabsim** [protomaps/PMTiles#362]
I am trying to use my pmtiles file with Mapbox and couldn't find any example on how to do so, please can you provide me with any example if available

**Comment by bdon** [comment]
What software or library are you referring to? "Mapbox" refers to many things, but if you mean Mapbox GL JS v2.0+ you generally need to load data from the Mapbox API.

**Comment by Mtehabsim** [comment]
@bdon Yes Mapbox GL JS, if the pmtiles is on s3 bucket, in MapLibre GL we define a Protocol, but for mapbox i guess I need to run the serve command on the bucket?

**Comment by bdon** [comment]
correct, you need to use any server-side or serverless function decoder, at that point it's a plain Z/X/Y tile endpoint you can add as a source in your style JSON. https://docs.protomaps.com/deploy/

Nothing else should be needed, so closing for now.

**Comment by am2222** [comment]
You can also use this package 

https://github.com/am2222/mapbox-pmtiles

I have tested it with raster and vector pmtiles.
