### ISSUE TITLE
Verify pmtiles crash

### ISSUE THREAD

**Issue by Mtehabsim** [protomaps/PMTiles#366]
I convert geojson file to pmtiles as the following:
`macbookpro@MacBooks-MacBook-Pro-2 Downloads % tippecanoe -o new.pmtiles new.geojson       
For layer 0, using name "new"
2 features, 175 bytes of geometry and attributes, 64 bytes of string pool, 0 bytes of vertices, 0 bytes of nodes
zsh: floating point exception  tippecanoe -o new.pmtiles new.geojson`

Which generates 'new.pmtiles' file with the size of 29KB

then i verify that the generated file is correct as:
`pmtiles verify new.pmtiles
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x280 pc=0x1281c02]

goroutine 1 [running]:
compress/gzip.(*Reader).Read(0x34610c0?, {0xc0002b7000?, 0x1010da5?, 0xc0000e11a0?})
	compress/gzip/gunzip.go:247 +0x22
bufio.(*Reader).fill(0xc0000e11a0)
	bufio/bufio.go:113 +0x103
bufio.(*Reader).ReadByte(0xc0000e11a0)
	bufio/bufio.go:272 +0x27
encoding/binary.ReadUvarint({0x28e8620, 0xc0000e11a0})
	encoding/binary/varint.go:136 +0x82
github.com/protomaps/go-pmtiles/pmtiles.deserializeEntries(0x4bb93418?)
	github.com/protomaps/go-pmtiles/pmtiles/directory.go:166 +0x18c
github.com/protomaps/go-pmtiles/pmtiles.Verify.func1(0x0?, 0x0?, 0xc00065f840)
	github.com/protomaps/go-pmtiles/pmtiles/verify.go:59 +0x17e
github.com/protomaps/go-pmtiles/pmtiles.Verify(0x215d7e0?, {0xc0000c49f0, 0x27})
	github.com/protomaps/go-pmtiles/pmtiles/verify.go:78 +0x7a4
main.main()
	github.com/protomaps/go-pmtiles/main.go:203 +0x765`
	
What might be the issue? the OS is Ventura 13.2.1
pmtiles 1.17.0 installed using brew

**Comment by bdon** [comment]
please upload your new.geojson and new.pmtiles so others can reproduce

**Comment by Mtehabsim** [comment]
In this folder I uploaded the used files
https://sagerdrones-my.sharepoint.com/:f:/g/personal/m_tehabsim_sagerdrone_com/EhULLTgEojFKlnozHpBuEw4Bp_j9bmaT-06lRbNtGlw1fQ?e=RUdDhc

**Comment by Mtehabsim** [comment]
I switched to linux and used older version of tippecanoe, used it to convert to new.mbtiles and then used pmtiles to convert to new.pmtiles and it worked so I guess the issue is in tippecanoe and especially in direct conversion of json file to pmtiles. 

@bdon Please advice should I close the issue?

**Comment by bdon** [comment]
you need to use https://github.com/felt/tippecanoe which is maintained, not mapbox/tippecanoe. 

please us that with `pmtiles` CLI v1.18 to verify
