### ISSUE TITLE
Serving to tiles changes the shape of the file

### ISSUE THREAD

**Issue by Mtehabsim** [protomaps/PMTiles#368]
I generated a pmtiles file, on the viewer it look as the following:
![Screenshot 2024-02-22 at 17 11 44](https://github.com/protomaps/PMTiles/assets/71636761/eac08b24-a75f-4a61-8123-5eb46a7773ee)
While when I run the serve function and use mapbox gl api to retrieve vector tiles on the map it looks like this:
![Screenshot 2024-02-22 at 17 12 45](https://github.com/protomaps/PMTiles/assets/71636761/ffa5357f-1f8c-4561-b7e4-cd30a701651e)

Any reason why this might happen?

**Comment by bdon** [comment]
you need to provide the style JSON you are using to assign colors to the tiled data.

**Comment by Mtehabsim** [comment]
@bdon sure, i am not talking about the color, I am talking about the added polygons which should be lines.

**Comment by bdon** [comment]
Yes, that comes from your style JSON which you have't provided

**Comment by Mtehabsim** [comment]
Execuse my question but why providing properties is important? If i dont care about the colors of the data and i provide the color for it using the add layer properties in Mapbox gl.

**Comment by bdon** [comment]
your style JSON determines whether you are using fill styles or line styles

**Comment by Mtehabsim** [comment]
got it, thanks
