### ISSUE TITLE
TypeScript fails to run? "./v2"

### ISSUE THREAD

**Issue by Terandium** [protomaps/PMTiles#375]
The index.ts file tries to import `import v2 from "./v2";`
But v2 doesn't exist, so it instantly panics and crashes..

![image](https://github.com/protomaps/PMTiles/assets/41748799/103f2fdf-6141-4cfb-9bd9-4c731570fbb0)
You see the v2 important, but v2 doesn't exist.
![image](https://github.com/protomaps/PMTiles/assets/41748799/06540ce0-c2f0-48d5-8122-d6445d1658da)

![image](https://github.com/protomaps/PMTiles/assets/41748799/b542e9a2-7271-4e6a-93d6-ad13967f2981)

Our tech stack is:
- Ignite (Expo)
- MapLibre GL JS
- iOS Simulator (Don't think it matters, but I havent run it on Android)

**Comment by bdon** [comment]
Can you post a runnable minimal example project so we can reproduce it and verify that a patch will fix it?

**Comment by Terandium** [comment]
> Can you post a runnable minimal example project so we can reproduce it and verify that a patch will fix it?

https://github.com/Terandium/pmtiles-ignite-issue

It’s just a blank ignite project, and I imported PMTiles in app.tsx

As it crashes on the import.

**Comment by bdon** [comment]
Should be fixed by https://github.com/protomaps/PMTiles/pull/376 , thanks for the repro case

(package.json was missing files for if your build doesn't use the bundled module in dist/)
