### ISSUE TITLE
Crash while using MapLibre and hosted protomaps version

### ISSUE THREAD

**Issue by pietervdvn** [protomaps/PMTiles#381]
Hi,

I'm using Protomaps with MapLibre on https://mapcomplete.org . This works as expected, but I get [this error](https://github.com/protomaps/PMTiles/blob/71e83f138a6f25e44624e763f9ae064f38492828/js/index.ts#L422) when intializing the map.

The URL is `https://api.protomaps.com/tiles/v3.json?key=2af8b969a9e8b692`; with the following request headers:

```
GET /tiles/v3.json?key=2af8b969a9e8b692 HTTP/2
Host: api.protomaps.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:122.0) Gecko/20100101 Firefox/122.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br, identity
Referer: https://api.protomaps.com/
Origin: http://127.0.0.1:1234
DNT: 1
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
range: bytes=0-16383
Connection: keep-alive
TE: trailers
```

This is an issue in Librewolf 122.0-2 (a firefox derivative), Chromium 123.0.6312.86 (Official Build) snap (64-bit) and Firefox 124.0 (64-bits)

**Comment by pietervdvn** [comment]
Nevermind, was an error in how I used the library

**Comment by bdon** [comment]
If you are using the hosted API, it's accessed via a Z/X/Y tile URL which MapLibre supports out of the box, there's no PMTiles client-side decoding necessary.
