### ISSUE TITLE
pmtiles.js: RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by jankulma** [protomaps/PMTiles#385]
Hi,

I created .pmtiles file by following "Getting Started" instructions (same extracted area around Utrecht), and I am able to view it https://maps.protomaps.com/. 

I wanted to serve it locally and render on a page.

I served the file with pmtiles executable:

`pmtiles serve ./my_area.pmtiles --port=8888 --cors=*`

As page template I used https://github.com/protomaps/PMTiles/blob/main/js/examples/maplibre.html

I replaced `PMTILES_URL` with `http://localhost:8888`

But the map does not render and in the console there is the error: `RangeError: Offset is outside the bounds of the DataView`

Also the pmtiles server returns no content (204): 
```
$ pmtiles serve ./my_area.pmtiles --port=8888 --cors=*
2024/04/13 12:05:47 main.go:150: Serving  ./my_area.pmtiles on port 8888 and interface 0.0.0.0 with Access-Control-Allow-Origin: *
2024/04/13 12:05:53 main.go:147: served 204 %2F in 20.582µs
2024/04/13 12:06:26 main.go:147: served 204 %2F in 18.279µs
2024/04/13 12:06:28 main.go:147: served 204 %2F in 19.823µs
2024/04/13 12:06:49 main.go:147: served 204 %2F in 42.102µs
```

I suspect this might be due to the fact that I am using a cropped area, and not the full map? (I dont want to use the full map though)

**Comment by bdon** [comment]
If you are using `pmtiles serve` you do not need to load the PMTiles library in your browser, you can access it as a typical Z/X/Y.mvt URL that MapLibre supports by default. Please see this issue: https://github.com/protomaps/go-pmtiles/issues/162

Suggestions welcome for how to clarify this

**Comment by jankulma** [comment]
Thanks!

>Suggestions welcome for how to clarify this

I'm not sure, probably its just that I'm a noob when it comes to maps / tiles and all this stuff. For ppl like me a beginner friendly step by step tutorial might help to clarify things like that.
