### ISSUE TITLE
cannot set fetch options with maplibre protocol

### ISSUE THREAD

**Issue by eknowles** [protomaps/PMTiles#397]
When using a custom `maplibre.addSource` to use pmtiles, the `PMTiles.getBytes` method uses the global `fetch` method, this is done during the read metadata stage I think.

This means users can not alter the options such as setting [credentials](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#sending_a_request_with_credentials_included)

https://github.com/protomaps/PMTiles/blob/main/js/index.ts#L379-L399

Once this has been read maplibre (i think) will then use the `loaders.gl` fetch methods which does allow the user to override this at a global level.

https://loaders.gl/docs/modules/core/api-reference/fetch-file

Could the pmtiles protocol also use this method so that users can fetch pmtiles using cors + credentials?

**Comment by bdon** [comment]
You can initialize a `FetchSource` with `CustomHeaders`:

https://protomaps.github.io/PMTiles/typedoc/classes/FetchSource.html

**Comment by eknowles** [comment]
How would that work with [addSource](https://maplibre.org/maplibre-gl-js/docs/examples/vector-source/)?

maplibre expects a string here both for `tiles` and `url`

**Comment by bdon** [comment]
See this example: https://github.com/protomaps/PMTiles/blob/main/js/examples/maplibre.html#L26

You can then reference it in a style via the same Url and it will resolve to the same instance

`new pmtiles.PMTiles(fetchSource)`

**Comment by reyemtm** [comment]
Would this be instead of using the built-in maplibre transformRequest? If pmtiles can use custom headers why noot just use the headers and create a fetch source internally using the existing headers?

**Comment by reyemtm** [comment]
And also, if we use this method with the custom FetchSource, does that mean we need a custom PMTiles for each url we want to use, rather than simply adding headers to all pmtiles requests like we can do with transformRequest?

For my use case I am just adding a header from a url query param in the PMTiles class, but would rather not use a custom fork. If you can point me in the direction to using the existing headers that's sent along with the request that would be awesome.

**Comment by bdon** [comment]
> built-in maplibre transformRequest

transformRequest does not apply to custom protocols.

> If pmtiles can use custom headers why noot just use the headers and create a fetch source internally using the existing headers?

There is no way to specify headers through MapLibre style URLs, you can only pass a string. 

> does that mean we need a custom PMTiles for each url we want to use

You need to instantiate a PMTiles javascript object and add it to the protocol for each URL, because there is no other way to specify it though the maplibre style object.

**Comment by bdon** [comment]
> using the existing headers that's sent along with the request

I don't know what this refers to?

**Comment by reyemtm** [comment]
I figured out your code after reading it through a few times, so here it is for those looking for how to do this:

```Javascript
    const pmtilesProtocol = new Protocol();
    maplibregl.addProtocol("pmtiles", pmtilesProtocol.tile);
    const authHeaders = new Headers({ Authorization: `Bearer ${userToken}` });
    const URL = "https://urltotiles.com/data.pmtiles";
    pmtilesProtocol.add(new PMTiles(new FetchSource(URL, authHeaders)));
```

But with this method I have to do this with all the pmtile urls I want to add. In Maplibre you can add headers to all/any requests via `transformRequest`, and it would be much simpler to use this method.  I think this would have to be defined in the Protocol class `instance`, as the custom headers are available there, but I'm not familiar enough with the code to know if those would get persisted throughout the code. If you don't want to support this that's fine, but could you something to the docs like `PMTiles does not support the transformRequest option in relation to custom headers, use the built-in FetchSource instead`.

```Javascript
const map = new maplibregl.Map({
    ...
     transformRequest: (url, resourceType) => {
        if (url.includes("pmtiles")) {
          return {
            url: url,
            headers: {
              Authorization: `Bearer ${userToken}`
            },
          };
        }
      }
  })
```

**Comment by reyemtm** [comment]
now that I look at this closer we can add the custom headers from `transformRequest` like this inside the Protocol class:
```Javascript
    const headers = new Headers({ ...(params?.headers || {}) });
    const source = new FetchSource(pmtilesUrl, headers);
    instance = new PMTiles(source);
```
Is this something you would be willing to add or accept a PR?

**Comment by bdon** [comment]
Updated the TypeDoc here: 

https://pmtiles.io/typedoc/classes/FetchSource.html
https://pmtiles.io/typedoc/classes/Protocol.html

> But with this method I have to do this with all the pmtile urls I want to add. 

Can you accomplish this using a loop or reusable function?

**Comment by bdon** [comment]
Custom headers example: https://github.com/protomaps/PMTiles/blob/main/js/examples/maplibre_headers.html

**Comment by lysek** [comment]
Is there any way to add `credentials: 'include'` to fetch requests? I have basic HTTP auth and I cannot load PMTiles file from that backend. I cannot use headers for this because HTTP basic credentials are not accessible to JS.

**Comment by bdon** [comment]
Currently there is not. Given that MapLibre accepts both headers and credentials as options https://maplibre.org/maplibre-gl-js/docs/API/type-aliases/RequestParameters/ it seems reasonable to add a `credentials: "same-origin" | "include" | ""` as an additional argument to FetchSource. any alternatives/opinions?

**Comment by lysek** [comment]
Yes, that is probably the best way.

I was thinking about adding the credentials property to methods of PMTiless that make fetch requests (`getHeader`, `getZxy`, ...) but that does not make much sense because the source can also be a local file.

**Comment by bdon** [comment]
Isn't it possible to implement HTTP Basic Auth on the client side by base64 encoding `user:pass` in the Authorization header?

I could add the `credentials` option to Fetch but I don't have any way to reproduce whether that is working correctly or not. If you want that please provide an example of how to test that functionality using a local HTTP server with basic auth.
