### ISSUE TITLE
Roads Missing

### ISSUE THREAD

**Issue by j** [protomaps/PMTiles#40]
I attempted to build my own tiles using OSM.

My workflow is:

```
osmium tags-filter socal-full.osm.pbf w/highway w/natural=water w/waterway=river w/water -o socal.osm.pbf
tilemaker --input socal.osm.pbf --output socal.mbtiles
pmtiles-convert socal.mbtiles socal.pmtile
```

TileMaker also layered in the coastline for me

When I view my map in MBTile format, I see all of the roads:

<img width="459" alt="image" src="https://user-images.githubusercontent.com/589410/164748804-eaa5732a-1989-4c46-8074-0c0308935f9e.png">

But viewing it in PMTiles after converting, I only see the ocean and lakes, no roads.  I used default styling and tried to override them to see if I can force a render somehow.

**Comment by bdon** [comment]
how are you viewing? the tilemaker default layers are different from the demo viewer for pmtiles. please include the code for your viewer.
