### ISSUE TITLE
PMTiles JS not working with latest Maplibre GL JS 4.x

### ISSUE THREAD

**Issue by larsschwarz** [protomaps/PMTiles#421]
Tried switching from Maplibre GL JS 3.x to 4.x, but this causes

```
Uncaught (in promise) TypeError: callback is not a function
    at pmtiles.js:746:13
```
This is the Protocol class within the getHeader fucntion which handles the JSON type (not using JSON, but an actual pmtiles URL).

I'm using the basic example code as provided in the repo like

```
let protocol = new pmtiles.Protocol();
maplibregl.addProtocol("pmtiles",protocol.tile);

let PMTILES_URL = "<FULL-URL-TO-PMTILES-FILE>";

const p = new pmtiles.PMTiles(PMTILES_URL)

// this is so we share one instance across the JS code and the map renderer
protocol.add(p);

// we first fetch the header so we can get the center lon, lat of the map.
p.getHeader().then(h => {
...
```

**Comment by bdon** [comment]
Did you upgrade to `pmtiles` 3.0.6? https://www.npmjs.com/package/pmtiles

**Comment by larsschwarz** [comment]
Yep, just double-checked to be sure.

**Comment by bdon** [comment]
I just updated the example https://github.com/protomaps/PMTiles/blob/main/js/examples/maplibre.html to MapLibre 4.5.0, can you identify how your code is different?

**Comment by larsschwarz** [comment]
Well that's odd. I didn't pull any updates of either MapLibre JS or PMTiles JS just switched back from MapLibre 3.3 to 4.5 and ... no issues! 🤷‍♂️ Must have been some cache issues? No idea. The only thing changed was the .pmfiles file itself and some styling.

Thanks Brandon!
