### ISSUE TITLE
Etag being spoofed by ClearURLs extension causes hard to understand errors

### ISSUE THREAD

**Issue by ginnyTheCat** [protomaps/PMTiles#427]
I stumbled across an issue where loading a `.pmtiles` file using the JS library worked on localhost or [pmtiles.io](https://pmtiles.io), but would error with random strings when loaded from the same origin as the one the file was on.

![Errors in the browser console consisting of random strings](https://github.com/user-attachments/assets/d2d19b0a-981e-4fb3-93ff-c2d3f1862adb)

After some digging I found out those errors were `EtagMismatch` errors with the etags randomly changing, none of which could be found in the network tab.

![Different Etag in the browser network tab](https://github.com/user-attachments/assets/6fc22ca6-3cd9-4a84-b2fe-5d119b054ba5)

The source of these randomized `Etag`s is a, to me unknown, feature of the [ClearURLs extension](https://addons.mozilla.org/en-US/firefox/addon/clearurls/), which seems to also [causes problems with S3 multipart uploads](https://github.com/ClearURLs/Addon/issues/177). I'm not quite sure whether this is an issue we should report to the extension developers or whether it might be worth to ignore `Etag`s in `pmtiles` in case they change with every response, instead of throwing a `EtagMismatch` error.

Because I did not set a CORS header allowing Etag, `fetch` filtered them out when pmtiles.io would request the file, causing it not to crash.

Disabling sending Etag headers for the `.pmtiles` in the nginx config fixed the problem, even if it's not ideal.

**Comment by bdon** [comment]
I think it's an issue to report to the extension developers because it will break many caching behaviors of browsers.

If you send a "weak" etag from nginx it will be ignored: https://github.com/protomaps/PMTiles/blob/main/js/index.ts#L402

>  to ignore Etags in pmtiles in case they change with every response

If this is a more systematic problem beyond this one extension then it is possible to keep a counter of how many eTag invalidations fail, and ignore eTags if more than one retry fails.

**Comment by ginnyTheCat** [comment]
I agree. I'm not quit sure why the error message does not contain `EtagMismatch`, just the one etag.

**Comment by bdon** [comment]
In our specific case this can be resolved by ClearURLs always returning a Weak ETag `W/...`, but I don't think that will resolve other issues with the extension. I open a PR to improve the error message: https://github.com/protomaps/PMTiles/pull/428

**Comment by bdon** [comment]
updated js to 3.0.7
