### ISSUE TITLE
Consumes all memory on large input

### ISSUE THREAD

**Issue by j** [protomaps/PMTiles#43]
I'm trying to convert a 66 GB file and it quickly consumes 32GB ram then stops.

Is there a solution to converting large files besides launching a super huge VM to handle conversions?

**Comment by j** [comment]
Update 2: Attempted to not compress, file writing stalls around 20GB with 100% CPU usage and 8% memory usage.

**Comment by bdon** [comment]
The python writer isn't particularly optimized for large use cases, but ideally it should work - that seems like too much ram consumption. What is the total # of tiles in the source (mbtiles?) and are there many duplicates?

**Comment by j** [comment]
I was able to finally have it finish. It gets to a point where nothing is
written to disk for minutes at a time. I couldn’t look too far into where
that happened.

It’s a planet file which filtered out highways at all zoom levels and
smaller roads starting at around zoom 6.

A constant status of what’s happening might be nice since I would tail the
output and not get activity in the file for very long times even on a huge
machine of 60 cores and 256gb ram.

**Comment by bdon** [comment]
OK, thanks for the report. So it sounds like this isn't a hang. The progress bar might be nice but I don't think there's a clean way to add it to this program without introducing more dependencies. It's likely either collecting deduplication hashes is taking up more and more time (hundreds of millions of hashes) which we could solve by limiting the hash to only tiles smaller than a certain size, or the sorting/pyramid construction takes too much time/ram.

**Comment by bdon** [comment]
[Go-pmtiles](https://github.com/protomaps/go-pmtiles) is now the preferred way to convert from mbtiles, which should be much more memory-efficient and shows a progress bar.
