### ISSUE TITLE
Fastly URLs to Stamen Map Tiles will no longer work

### ISSUE THREAD

**Issue by mizmay** [protomaps/PMTiles#440]
Still used in example here:

https://github.com/protomaps/PMTiles/blob/bcd5571ba5f76c297b23f7a6405a2ddea339c8bf/python/examples/create_raster_example.py#L15

Migration guide:

https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/

Though you may already have a solution.

**Comment by bdon** [comment]
Fixed in https://github.com/protomaps/PMTiles/pull/441, thanks!
