### ISSUE TITLE
Intermittent Magic Number error with S3+CloudFront

### ISSUE THREAD

**Issue by TheMapSmith** [protomaps/PMTiles#442]
We have a user who frequently encounters an error that, despite our best efforts, we have yet to reproduce. 

```
Error: Wrong magic number for PMTiles archive
```

On this page, the PMTiles file is filtered based on state FIPS, and then it zooms to that state. Their map renders like this: 

| Rendering with Error | Expected Rendering |
| - | - |
| ![chrome_Ui5MJFQofN](https://github.com/user-attachments/assets/e5967d4a-3213-4883-8628-c8038679e46c) | ![chrome_wNFHG78G1u](https://github.com/user-attachments/assets/81ff0459-0cb2-47e2-bb22-101f82e5577d) |

This is the page they were trying to load when they encountered the error. This happens on all State pages for him, though.
* https://trueviews.org/massachusetts/

Tech stack:
* Website code on GitHub Pages 
* MapLibre for rendering 
* PMTiles stored on S3 with CloudFront 

This is the URL to the PMTiles in the screenshots that failed to load. This file is 3.6 GB. 
* https://dngd4vlxpflqq.cloudfront.net/nationwide-zcta.pmtiles

We have similar files for other Census geographies as well. I'm not clear whether this happens more with a particular PMTile file. 

The other issues I found reporting this error don't have applicable solutions. 
* #283
    * They have the PMTiles on GH Pages using LFS, which isn't supported. Our files are in S3
* #402
    * They put Lambda between PMTiles and the user, so they need to use `z/x/y/` URLs instead. We directly access the PMTiles with MapLibre. 

Do you have any idea why this could be happening? Are there steps we can take to try to reproduce it? Thanks in advance!

**Comment by bdon** [comment]
Is it possible they are behind some corporate or school firewall that is returning some blocked page HTML for that URL?

Can you have them open the web console and show what the actual content of the successful 206 response for the `.pmtiles` is?

**Comment by tylerlu-hivemapper** [comment]
We have a very similar setup as yours (S3, maplibre) and are running into the same issue. Curious if you were able to find out more about this?

**Comment by TheMapSmith** [comment]
Hey Brandon, thanks for getting back to me so quickly! 

I checked, and he is mostly experiencing the issue at home, not at work behind an academic firewall. 

He shared his Chrome Extensions with me: 

![image (20)](https://github.com/user-attachments/assets/3e3bddc6-71c4-4c79-9899-cd86efb4a024)

He says he rarely uses the VPN and only turns it on to stream from other countries. 

He reports that once the error starts happening, he can't use the website at all until he restarts his browser and clears his cache. 

I'm not sure what exactly you'd want to see from the `206` response, but he shared this screenshot from his network panel. 

![snip2](https://github.com/user-attachments/assets/1b6b8fd8-0f3f-411f-a210-e9075215eaa6)

**Comment by bdon** [comment]
Thanks for the screenshot. It looks like in that case the map is working?

It would be valuable for him to provide, in the case that he sees the "Magic Number" console error and the map stops working, the contents of the "Preview" tab (one to the right of the Headers tab)

**Comment by TheMapSmith** [comment]
Here's a screenshot from him of the Preview tab: 


![snip4](https://github.com/user-attachments/assets/47e19be9-5b83-424d-b12d-7a1d5ebe486b)

While the national data did load successfully, the behavior of the page did not finish executing due to the error. 

Upon browsing to `/arizona,` the expected behavior is:
1. Load the national map 
2. Filter PMTiles to only Arizona data
1. Zoom to Arizona's extents

**Comment by TheMapSmith** [comment]
I was able to reproduce the issue on my end finally. I haven't tracked down the specific scenario in which this happens, but I'm able to inspect `pmtiles.js` when it occurs. 

The tiles that fail are when the browser looks to the disk cache for the data. In those situations, the Preview shows:

```
NULNULNULNULNULNULNULNULNULNUL.... 
```
(repeats for 16,384 chars total)

When pausing here in Dev Tools:

https://github.com/protomaps/PMTiles/blob/df23fa6320d23558cc8ba169bae408049e79d283/js/index.ts#L572

The response data looks like: 
![chrome_OSg7z35qhl](https://github.com/user-attachments/assets/0246b3a6-0d6f-4145-b05c-33ac7310d24f)

Let me know if there are additional debugging steps you'd like me to take.

**Comment by bdon** [comment]
The 16384-byte request only happens on the first load of the tileset, not individual tiles, so somehow that is being retrieved from the browser as all zero values? 

If you disable the disk cache completely are you able to reproduce? Can your user reproduce on non-Chrome browsers?

**Comment by bdon** [comment]
@TheMapSmith also, are you updating the `.pmtiles` on storage regularly or has it been the exact same file the entire time?

**Comment by TheMapSmith** [comment]
I still haven't identified a pattern that triggers this. The only time I've been able to reproduce this is after aggressively clicking around and navigating between pages. 

> first load of the tileset 

Depending on what exactly this means, this only happens to me after browsing for a while. I haven't had it happen on the first pageload of a session. 

> If you disable the disk cache completely are you able to reproduce?

I just aggressively clicked around for 10 minutes with Disable Cache turned on and couldn't reproduce the bug, so that feels like a good clue. 

> updating the .pmtiles on storage regularly

The data hasn't changed since September 3rd. 

One theory we have is that we're overloading the browser. Since we reference nine different pmtile sources, we declare them all in our MapLibre style. Apparently, this causes each source to get pinged each time a Map is created. We will try switching the approach to creating and removing pmtile sources as the user makes selections on the map and let you know how it goes.

**Comment by bdon** [comment]
I wonder if there is some overlap with #384 #445 .

@TheMapSmith have you attempted to reproduce this with a non-Chromium based browser, like Safari or Firefox?

Can you provide the specific Chrome version you are using to reproduce?

**Comment by TheMapSmith** [comment]
That does feel like it is relevant! Glad to see the thread is still active this year. 

FWIW, this [stress-test HTML page](https://issues.chromium.org/issues/40542704#comment53) didn't result in the error... 🤔 

I wonder if the request isn't "failing" in the network sense there, but the response isn't valid PMTile data?

**Comment by bdon** [comment]
`network-issue.html` - I can reproduce the error on Chrome and Edge on Windows, but not on Arc on Mac (also Chromium-based) I had to wait about a minute before the console errors started to show up

**Comment by bdon** [comment]
here is a ZIP build of the JS library based on this heavy-handed workaround around this branch:

https://github.com/protomaps/PMTiles/compare/main...chrome-windows-cache-workaround

[pmtiles-3-0-7-chrome-workaround.js.zip](https://github.com/user-attachments/files/16987893/pmtiles-3-0-7-chrome-workaround.js.zip)

**Comment by TheMapSmith** [comment]
Nice! I tested this locally and clicked around for ~10 minutes without encountering the error! I wish I had a method that consistently reproduced the error, though.

**Comment by conbrad** [comment]
I also have users with this issue, Chrome on Windows if that helps. PMTiles are hosted on an S3 compatible object store and fetched with a `PMTilesVectorSource` from `ol-pmtiles`. Also unable to reliably reproduce it.

**Comment by bdon** [comment]
`pmtiles.js` v3.1.0 has this workaround built in. https://www.npmjs.com/package/pmtiles

**Comment by conbrad** [comment]
> `pmtiles.js` v3.1.0 has this workaround built in. https://www.npmjs.com/package/pmtiles

Thanks for shipping the workaround so quickly @bdon !

Confirmed this is working for Chrome users on Windows.

**Comment by ycouble** [comment]
Having the same issue on protomaps-leaflet, unable to reproduce myself.

I tried upgrading protomaps-leaflet to 5.0.0, but I'm not sure it contains the workaround mentionned here. @bdon is this the case ?

**Comment by bdon** [comment]
It uses the caret specifier `^3.0.7` which should install v3.2.0 as that is the latest major version compatible release.
