### ISSUE TITLE
Different results across browsers

### ISSUE THREAD

**Issue by m-mohr** [protomaps/PMTiles#445]
I'm loading various fiboa datasets into the Viewer, for example https://data.source.coop/fiboa/de-th/de-th.pmtiles

If I load https://pmtiles.io/?url=https%253A%252F%252Fdata.source.coop%252Ffiboa%252Fde-th%252Fde-th.pmtiles it gives very different results depending on the Browser:

### Firefox 130.0 (Win64) works fine

![grafik](https://github.com/user-attachments/assets/62477db5-09fd-4a0d-afc4-41d7a58ecbb1)

### Chrome 128.0.6613.120 (Win64) shows unexpected blocks

![grafik](https://github.com/user-attachments/assets/c880ca93-ddfa-41b1-8987-999842669b56)

### Edge 128.0.2739.67 (Win64) shows nothing

![grafik](https://github.com/user-attachments/assets/e6231b25-8412-4102-8d41-43ca86107887)

---

I have a similar issue on https://fiboa.org/map/ where it only shows data in Firefox (after zooming in).

Any clue why this happens? Is this an issue of the dataset or an issue with the browsers?

**Comment by m-mohr** [comment]
No

**Comment by bdon** [comment]
What if you disable your browser cache?

**Comment by bdon** [comment]
with Edge: Version 128.0.2739.67 (Official build) (64-bit)

![Screenshot 2024-09-11 162835](https://github.com/user-attachments/assets/30d86d37-74e6-4019-b647-bba245b31c98)

**Comment by christophfriedrich** [comment]
I'm that friend :D

Sorry Matthias, using this pmtiles.io website I get the same result as Brandon (my Edge says it's version 128.0.2739.63). Just the fiboa map shows nothing. So maybe it has more to do with the integration in MapLibre vs. OpenLayers?

**Comment by m-mohr** [comment]
Hmm, looking at it again today, I see "failed to fetch" errors in the console now. Weird...

Anyway, I'm also not sure how to fix https://fiboa.org/map/

**Comment by m-mohr** [comment]
Oh https://fiboa.org/map/ works today on Edge and Chrome. Does it also work for you today, @christophfriedrich ?

**Comment by christophfriedrich** [comment]
I checked when writing the other comment and it wasn't working, but now I checked again with disabled cache and it does indeed work. Maybe the data sent out yesterday was somehow corrupted? Anyway, it definitely doesn't seem to be an issue with this package here.

**Comment by christophfriedrich** [comment]
I managed to provoke another failure in Edge: I disabled the cache again, and while some areas were loaded correctly, others were not. Note how one request to `de-th.pmtiles` succeeded and the other not. I'm speculating it may be because in principle the file exists in the cache, but not the needed range and this condition is not resolved correctly?

![grafik](https://github.com/user-attachments/assets/737e3c57-815c-4e07-a044-4a33513959a3)

This is the request that failed, which worked perfectly fine when executed in the console:

```
curl 'https://data.source.coop/fiboa/de-th/de-th.pmtiles' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Microsoft Edge";v="128"' \
  -H 'Referer: https://fiboa.org/' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0' \
  -H 'range: bytes=3552503-4009370' \
  -H 'sec-ch-ua-platform: "Windows"'
```

**Comment by tim-salabim** [comment]
Not sure if it helps, but the second url from the original post gives me (in firefox and chromium):

![image](https://github.com/user-attachments/assets/4c053346-1315-4830-9f47-99aa963b8cdb)

**Comment by christophfriedrich** [comment]
That was just the URL being encoded twice -- delete every `25` after a `%` sign and it works: https://pmtiles.io/?url=https%3A%2F%2Fdata.source.coop%2Ffiboa%2Fde-th%2Fde-th.pmtiles

**Comment by tim-salabim** [comment]
Ah, ok. Sorry for the noise

**Comment by bdon** [comment]
@christophfriedrich @m-mohr we have a workaround proposed in https://github.com/protomaps/PMTiles/issues/442#issuecomment-2347943421

This effectively disables caching of byte ranges in the browser for Chromium-based browsers on windows, based on this Chromium issue: https://issues.chromium.org/issues/40542704

**Comment by bdon** [comment]
`pmtiles.js` 3.1.0 and `ol-pmtiles` 1.0.2 have the Chrome+Windows workaround.
