### ISSUE TITLE
aws lambda function throws dynamic require error

### ISSUE THREAD

**Issue by carlojoerges** [protomaps/PMTiles#448]
Hi!
I followed the instructions at https://docs.protomaps.com/deploy/aws 
When I call the lambda function it errors out with:
`2024-09-11T15:45:34.910Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "Dynamic require of \"http\" is not supported",
    "stack": [
        "Error: Dynamic require of \"http\" is not supported",
        "    at file:///var/task/index.mjs:13:9",
        "    at node_modules/@smithy/node-http-handler/dist-cjs/index.js (file:///var/task/index.mjs:520:23)",
        "    at __require2 (file:///var/task/index.mjs:16:50)",
        "    at file:///var/task/index.mjs:2591:40",
        "    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)",
        "    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)",
        "    at async _tryAwaitImport (file:///var/runtime/index.mjs:1008:16)",
        "    at async _tryRequire (file:///var/runtime/index.mjs:1057:86)",
        "    at async _loadUserApp (file:///var/runtime/index.mjs:1081:16)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)"
    ]
}
`

I tried compiling the index.mjs from the repository myself but am getting the same result.

**Comment by bdon** [comment]
Can you try using this CloudFormation stack instead:

https://pmtiles.io/cloudformation-stack.yaml

I should be updating the docs today to use the new, simpler and automated CloudFormation method.

Will double check the issue with `http`.

**Comment by bdon** [comment]
The manual setup has been superseded by CloudFormation here: https://docs.protomaps.com/deploy/aws

I did fix the original http://pmtiles.io/lambda_function.zip which should now be the same build output as above. 

Let me know if there are issues with the above (it's brand new)

**Comment by carlojoerges** [comment]
perfect, the cloudformation worked flawlessly
