### ISSUE TITLE
ol-pmtiles v1 import breakage

### ISSUE THREAD

**Issue by conbrad** [protomaps/PMTiles#451]
Hi,

We have an [open PR](https://github.com/bcgov/wps/actions/runs/10894194014/job/30230515616?pr=3926#step:10:241) to bump `ol-pmtiles` from `0.5.0 -> 1.0.0` but our tests break with this error:

```
Error: Cannot find module 'wps/web/node_modules/ol/source/DataTile' imported from wps/web/node_modules/ol-pmtiles/dist/esm/index.js
Did you mean to import "ol/source/DataTile.js"?
```

We run node 20 but I also tried with 18.

`ol`/`ol-pmtiles` combination is:
```
    "ol": "10.0.0",
    "ol-pmtiles": "^1.0.0",
 ```
 
 Also tried bumping `ol`.

**Comment by bdon** [comment]
Seems odd that the resolution by the bundler (vite) isn't inferring `.js` but we can change it to use `import .js` like in the OL examples: https://openlayers.org/en/latest/examples/data-tiles.html

**Comment by bdon** [comment]
Can you try ol-pmtiles 1.0.1?

**Comment by conbrad** [comment]
> Can you try ol-pmtiles 1.0.1?

Yep works, thanks for the quick turnaround on that @bdon !
