### ISSUE TITLE
Feature question: strip prefix

### ISSUE THREAD

**Issue by aapeliv** [protomaps/PMTiles#457]
Context: we serve a bunch of stuff from Cloudfront. I'd like to deploy static map tiles under a sub-path like `/maps/tiles/` like `https://cdn.example.com/maps/tiles/20240918/1/0/1.mvt`. However, at the moment the serverless function doesn't allow doing things (I think I could rename my PMTiles file to `maps/tiles/20240918.pmtiles` in the bucket?).

I am probably going to hack in a feature to strip the prefix `/maps/tiles` into a fork based on an env var, but wondering if there is interest in accepting a PR for it and what that would entail?

**Comment by aapeliv** [comment]
I've sorted out what I need to do by adding an env var that lets you just set the PMTiles path to whatever: https://github.com/protomaps/PMTiles/pull/456/commits/1fa5ebe0529ba1c8eb01b211718af97eacd5fb17. Obviously only works if you have that path serving a single file.


Also, unrelated, but thank you for this awesome project! It was also super easy to build this function and hack on it, I'm impressed by that too!

**Comment by bdon** [comment]
> However, at the moment the serverless function doesn't allow doing things (I think I could rename my PMTiles file to maps/tiles/20240918.pmtiles in the bucket?)

Yes, this is the intended solution. Prefix your object keys with the prefix you want. 

> Obviously only works if you have that path serving a single file.

That could work in your fork but isn't a general-purpose solution. There is an existing `PMTILES_PATH` which does kind of the opposite of what you want: if you already have a bucket structured with the prefixes `/mytiles/abc.pmtiles`, setting `PMTILES_PATH` to `/mytiles/{name}` will let the requests to `/abc` fetch from that archive.

**Comment by bdon** [comment]
@aapeliv is re-organizing the objects in your bucket to match your desired URL layout a sufficient solution?

I thought a bit about how to configure a prefix-based `PMTILES_PATH` but we would need to extend it to be a regular expression or something similar to how [nginx rewrite rules](https://blog.nginx.org/blog/creating-nginx-rewrite-rules) work. That seems too complex for limited gain, so I'm going to close this issue as non-actionable. Let me know if you have other ideas or your bucket situation isn't compatible with the above.

**Comment by aapeliv** [comment]
Hey @bdon, yes what I’ve good currently is more than satisfactory for my use case!

Yes I agree that it’s not clear how to do it in a sensible way in general, especially since I seem to be one of very few looking for this kind of feature!
