### ISSUE TITLE
Expected? Multiple range requests per pageload

### ISSUE THREAD

**Issue by TheMapSmith** [protomaps/PMTiles#468]
Hey Brandon, I'm debugging some performance issues for a client and I noticed something interesting in the network panel and I want to confirm whether this is expected or not. 

We have a few PMTiles layers [in a map](https://edit.zoningatlas.org/atlas/). When watching the requests, there are around a dozen requests per PMTiles file. 

![image](https://github.com/user-attachments/assets/865a011b-e12f-4aef-b439-d82cbb7a1593)

I'm guessing that this is because each request needs a different byte range. A sample of the response headers:
* bytes 72726246-72879088/28868822500
* bytes 72879089-72988895/28868822500
* bytes 72396543-72506905/28868822500
* etc. 

Is this the intended behavior, or do we need to adjust our implementation?

**Comment by bdon** [comment]
that is correct, each tile is a separate range request and downloaded independently.

**Comment by TheMapSmith** [comment]
Good to know 👍 

Hopefully, this issue will help any folx in the future who are curious about this as well 😄
