### ISSUE TITLE
Failed to fetch errors 

### ISSUE THREAD

**Issue by nmondon** [protomaps/PMTiles#493]
Hi and thanks for all the work!

I'm using maplibregl@4.7.1 and pmtiles@3.2.1 with an hosted pmtiles files on google cloud storage. 

- I've some old pmtiles files generated with the previous PMTiles cli (the style is managed by protomaps-themes-base@3.X) that work without any issue. 

- But, I've also tried the new pmtiles cli (@1.22.1) and extracted a new pmtiles file on my cloud storage. I've used the new version of protomaps-themes-base (@4.X) to style it. Works quite well but I'm encountering lots of "Failed to fetch" errors on certain levels of zoom. 

I'm on MacOS m3 and Chrome. I've seen some other issues that look similar, #442 for instance, but I'm not sure this is exactly the same pb. 

Don't hesitate if you need more details on my setup.

<img width="1725" alt="Screenshot 2024-11-12 at 15 00 50" src="https://github.com/user-attachments/assets/78b88946-4e45-40dd-b4a6-6739571201fb">

**Comment by bdon** [comment]
Can you check the network tab to see which URL is failing? Is it possible you do not have a valid `sprite`key in your style?

**Comment by nmondon** [comment]
Sure, I'll check that and let you know. Thanks!

**Comment by nmondon** [comment]
Sorry for the delay. I relaunch the build of the pmtiles and everything went fine this time... I really don't know what went wrong... 

Anyway, thanks for the help and your fantastic job!
