### ISSUE TITLE
Use range value in url request params instead of cache no-store

### ISSUE THREAD

**Issue by ale-siradel** [protomaps/PMTiles#496]
Hello, 

https://github.com/protomaps/PMTiles/blob/bbeda97ed44d10b785e99f0dfe430b5728baec95/js/index.ts#L421

Why not using the range value in url's request params instead of cache no-store? 
This allows to preserve cache usage and avoid the conflict on cache entry. Urls will be distinct, cache entries too.

**Comment by bdon** [comment]
Because of a Chromium bug: https://github.com/protomaps/PMTiles/issues/442

**Comment by ale-siradel** [comment]
yes, for the browser, this is not the same resource. So, there is no cache concurrent access. 
But truth is.. still sad if we can t benefit from cache. 
I ve my own server, so I thinking making an alternative version of the FetchSource. Replacing the use of range header by a request param. In my context, that is ok. No chrome's bug and cache ok
