### ISSUE TITLE
PMTiles assertionerror error for MBTiles file

### ISSUE THREAD

**Issue by juanignaciosl** [protomaps/PMTiles#56]
If you run `pmtiles-convert --gzip WFIGS_-_2022_Wildland_Fire_Perimeters_to_Date.mbtiles WFIGS_-_2022_Wildland_Fire_Perimeters_to_Date.pmtiles` (MBTiles file is attached), it fails with the following error:

```
(...)
  File "(...).venv/lib/python3.9/site-packages/pmtiles/writer.py", line 131, in _write_header
    assert len(metadata_serialized) < 140625
AssertionError
```

metadata_serialized len is `168067`.

```
$ pip show pmtiles
Name: pmtiles
Version: 2.0.0
```

[WFIGS_-_2022_Wildland_Fire_Perimeters_to_Date.mbtiles.zip](https://github.com/protomaps/PMTiles/files/9131559/WFIGS_-_2022_Wildland_Fire_Perimeters_to_Date.mbtiles.zip)

**Comment by bdon** [comment]
hmm, yeah I was worried about this. Do you depend on reading the generated `tilestats` created by tippecanoe? If not, can you use `--no-tile-stats` to see if that gets under the required size?

The next spec revision should have no limit on JSON metadata.

**Comment by juanignaciosl** [comment]
Right now there's no need to read the generated tilestats, but that's likely to change soon. Using `--no-tile-stats` works at the moment, but removing the limit if possible would be better. Thanks!
