### ISSUE TITLE
pmtiles-convert Attribute Error

### ISSUE THREAD

**Issue by mem48** [protomaps/PMTiles#68]
I'm getting a python AttributeError when converting a .mbtiles file to .pmtiles

```
pmtiles-convert postcode.mbtiles postcode2.pmtiles
('compression:', 'disabled')
Traceback (most recent call last):
  File "/home/malcolm/.local/bin/pmtiles-convert", line 38, in <module>
    mbtiles_to_pmtiles(args.input, args.output, args.maxzoom, args.gzip)
  File "/home/malcolm/.local/lib/python2.7/site-packages/pmtiles/convert.py", line 40, in mbtiles_to_pmtiles
    writer.write_tile(row[0], row[1], flipped, force_compress(row[3], gzip))
  File "/home/malcolm/.local/lib/python2.7/site-packages/pmtiles/convert.py", line 15, in force_compress
    return gzip.decompress(data)
AttributeError: 'module' object has no attribute 'decompress'
```
[postcode.zip](https://github.com/protomaps/PMTiles/files/9436689/postcode.zip)

**Comment by mem48** [comment]
I also tried the gzip option as the error mentions compression, and got a different error

```
pmtiles-convert postcode.mbtiles postcode2.pmtiles --gzip
('compression:', 'gzip')
Traceback (most recent call last):
  File "/home/malcolm/.local/bin/pmtiles-convert", line 38, in <module>
    mbtiles_to_pmtiles(args.input, args.output, args.maxzoom, args.gzip)
  File "/home/malcolm/.local/lib/python2.7/site-packages/pmtiles/convert.py", line 40, in mbtiles_to_pmtiles
    writer.write_tile(row[0], row[1], flipped, force_compress(row[3], gzip))
  File "/home/malcolm/.local/lib/python2.7/site-packages/pmtiles/writer.py", line 101, in write_tile
    hsh = hash(data)
TypeError: writable buffers are not hashable
```

**Comment by bdon** [comment]
@mem48 can you check you are using python version 3?

**Comment by mem48** [comment]
Thanks, that fixed it! I'm not a regular python user so making noob errors. 

I might have missed it, but I don't think the readme says that Python 3 is a requirement.

**Comment by mem48** [comment]
I'm on a work computer that is fairly locked down, but I have a Windows Subsystem for Linux with Ubuntu 18.04.6 LTS which lets me play around with command line programs. I know it is out of date, but I only use it regularly to run tippecanoe which it does well.

**Comment by bdon** [comment]
@mem48 ok, thanks for the info. Moving forward

* the pmtiles command line program will be a standalone binary that does not need a python installation, it will be downloadable through GitHub releases at GitHub.com/protomaps/go-pmtiles for linux (and maybe windows) - so the `pmtiles-convert` through python will be essentially deprecated
* the tippecanoe fork in GitHub.com/protomaps/tippecanoe should output pmtiles directly soon with `-o filename.pmtiles`

**Comment by tim-salabim** [comment]
@bdon that's awesome!
