### ISSUE TITLE
pmtiles-convert does not appear to install in windows

### ISSUE THREAD

**Issue by Medit8r** [protomaps/PMTiles#77]
When I follow your documentation, this is what I see:

![image](https://user-images.githubusercontent.com/113394273/191588934-f06226e7-b20b-48cf-a0cd-5e505e5d7c1e.png)

**Comment by bdon** [comment]
You will need to determine the `bin` path that is associated with your `pip` installation, the `pmtiles-convert` program should exist in there.

**Comment by bdon** [comment]
The preferred way to covert to PMTiles is now here: https://github.com/protomaps/go-pmtiles/releases/tag/v1.0.2 which has a windows binary. running `pmtiles convert input.mbtiles output.pmtiles` will create the v3 format, which is readable by the inspector at https://protomaps.github.io/PMTiles/ but not the published libraries yet.

**Comment by bdon** [comment]
Closing for now, please report in [go-pmtiles](https://github.com/protomaps/go-pmtiles) if you have Windows-specific issues.
