### ISSUE TITLE
pmtiles-serve serves tiles with TMS scheme

### ISSUE THREAD

**Issue by typebrook** [protomaps/PMTiles#8]
Problem: Now `pmtiles-serve` directly uses `y` value in sqlite table `tiles` from MBTiles, which is TMS scheme.

In fact, [MBTiles always follow TMS scheme](https://github.com/mapbox/mbtiles-spec/blob/6643d4daca3f7417e4f2068fb3974aadb0a1154d/1.3/spec.md#content-1). So if we want to serve tiles with XYZ scheme, the `y` value should be
```bash
# y is the value in MBTiles
2^z - 1 - y

**Comment by bdon** [comment]
@typebrook can you try with version 0.0.5?

**Comment by typebrook** [comment]
@bdon Looks good! Well done!
