### ISSUE TITLE
protomaps.com issues

### ISSUE THREAD

**Issue by jcary741** [protomaps/PMTiles#86]
Hello @bdon ,
I didn't know how else to contact you, so I'm submitting this here:
The signup form on protomaps.com is not working, and clicking "support" just redirected me to the docs page.

I was signing up to hopefully learn more about Mantle.

Cheers,
Jay

**Comment by bdon** [comment]
@jcary741 thanks for letting me know, I fixed the signup error.  

I'm in the midst of updating the site this week, but Mantle is becoming open source and won't require a signup - you can contact me at brandon@protomaps.com if you'd like to try it out
