### ISSUE TITLE
ETag problems in JavaScript client + passing through other metadata

### ISSUE THREAD

**Issue by bdon** [protomaps/PMTiles#90]
If the new resource has a new ETag but it shorter than the previous, the server might return `416 Range not Satisfiable`, which does not have an accompanying ETag. This will invalidate the header, but present a bunch of errors in the console.

We should unify on using the [`If-Match` header in sending the requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Match), which will return `412 Precondition Failed` in the mismatch case, which is designed for this specific situation.

**Comment by bdon** [comment]
@cquest @msbarry I think I encountered an edge case where even `If-Match` won't be effective. If the header request (first 16 bytes) is cached by the browser itself, say with ETag `aaa`, it may be returned to the JS client to fetch a tile. If the tile responds with ETag `bbb` or even has `If-Match`:`aaa`, we need to fetch the header again.

However, since the first header we got was from the browser cache, we can't simply ask for the header again, since we will get the browser cache response. So it seems like we need to add another parameter to HTTP sources like `forceNoCache:bool` to force a `cache-control: no-cache` on any "retry" code paths.

Another fix would be to always send `cache-control: no-cache` for every first 16 kB request, but that makes that one request never cacheable across browser sessions.

**Comment by bdon** [comment]
I think the above situation can be resolved by adding state to the `FetchSource`: if we're requesting the header for a given URL the 2nd time, add `fetch(..., {cache:'reload'})`: https://developer.mozilla.org/en-US/docs/Web/API/Request/cache

**Comment by bdon** [comment]
I've resolved this by using `cache: reload` and Response ETag logic, instead of using conditional requests with `if-match`. Version 3.0.0-alpha.2 should support this, please test if you can with in-place updates on your storage; I plan to release 3.0.0 this week.

**Comment by bdon** [comment]
Released in js v3.0.0

**Comment by forgotPassword** [comment]
@bdon, observations @3.0.2:

1. Using a world tile, and than swapping to a city tile:
- 416 response
- 9 same requests to first 16kb 

Is it possible to send just 1 request? Abort others?

2. Other way around, start from a city tile, and update with a world tile:
- 9 range requests
- 9 first 16kb requests
- map does not load/show tiles beyond original small city bounds

**Comment by bdon** [comment]
* How do I reproduce the 9 requests?
* What web browser are you using?

**Comment by forgotPassword** [comment]
Latest chrome. I load MapLibre with zoom 14 and and some Center coordinates. Then rename the file on the server. Zoom out.

![network](https://github.com/protomaps/PMTiles/assets/3125689/cbb3201b-066e-482b-9ad0-26210f264c3e)

**Comment by bdon** [comment]
What if you uncheck disable cache? 

Does the new contents show up correctly?

**Comment by forgotPassword** [comment]
Same behavior with disable cache unchecked.

**Comment by bdon** [comment]
> map does not load/show tiles beyond original small city bounds

Yeah, this is a limitation of the way the bounds are communicated to MapLibre. I don't see an obvious way right now to fire an event on etag invalidation that dynamically changes the maplibre bounds. 

Will push a patch release to optimize the N header requests where N is the number of tiles needed to cover your screen

**Comment by bdon** [comment]
@forgotPassword please try v3.0.3

**Comment by forgotPassword** [comment]
Looks good, only 1 16kb request. Thanks!

There is a slight difference in the logic depending if the server returned 416.

- 416 -> immediately follows with the 16kb request.
- New Etag ->9 range requests -> 1 16kb.

**Comment by bdon** [comment]
Yeah, that isn't avoidable because each request for a tile proceeds independently, so 9 separate requests for a stale range will return a mismatched etag.
