### ISSUE TITLE
Content-Length mismatch indicates byte serving not supported; aborting.

### ISSUE THREAD

**Issue by wipfli** [protomaps/PMTiles#93]
When I update my .pmtiles file on GitHub pages and reload my maplibre map, I get this error from time to time:

![image](https://user-images.githubusercontent.com/53421382/200133875-c65f2afd-4bbd-4007-8237-2f10e0ee847d.png)

**Comment by wipfli** [comment]
Sorry for not posting steps to reproduce, I don't know how I can reproduce this really...

**Comment by wipfli** [comment]
Here is the commit that I did before this crash: https://github.com/wipfli/swiss-map/commit/035aa35c540bc45900ec372f9337ddd5ebd3bba2

**Comment by bdon** [comment]
Does this appear randomly only after a new commit or update to the file? What browser are you using?

**Comment by wipfli** [comment]
I use chrome on ubuntu. Sometimes I get the error when I update the pmtiles file, and sometimes not. I can have a look if I find a way to reproduce this.

**Comment by bdon** [comment]
@wipfli can you upgrade to 2.6.0 and observe to see if this still happens? The logic for fetch is a bit more tolerant, but mostly affects archives less than 16 kb (very small)

**Comment by wipfli** [comment]
Ah interesting. For the map where I saw this problem I switched to the cloudflare z/x/y endpoints. But next time I use the maplibre plugin will use v2.6.0. Since I never made a good reproduction of this bug, I wonder if I should keep the issue open or just close it?
